<?php return array(
	array(
		'message' => 'Document root, no rewrite, called root',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62231',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62231',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62234',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62239',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php/fubar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/index.php/fubar',
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62246',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/index.php/fubar',
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'Agavi=8c71c4284bc299552c617e8fe12ed99e',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '57019',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'test=foo%20bar+baz',
			'REQUEST_URI' => '/index.php/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fo o&ba+r',
			'PHP_SELF' => '/index.php/fo o&ba+r',
		)
	),
	array(
		'message' => 'Document root, rewritten, called root',
		'input' => '/',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62251',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62256',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/fubar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62256',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REQUEST_URI' => '/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
	array(
		'message' => 'Document root, rewritten, called special path with query',
		'input' => '/fo o&ba+r',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://localhost/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fo_o' => '',
			'ba_r' => '',
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'Agavi=8c71c4284bc299552c617e8fe12ed99e',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fo o&ba+r',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '57011',
			'SCRIPT_FILENAME' => '/Library/WebServer/Documents/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REQUEST_URI' => '/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/index.php',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/index.php',
			'PHP_SELF' => '/index.php',
		)
	),
);