<?php

/**
 * Data file for Africa/Abidjan timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/25/2008 11:59:58
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830383032,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1913,
  ),
  'name' => 'Africa/Abidjan',
);

?>