<?php

/**
 * Data file for Africa/Johannesburg timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 01/29/2009 09:07:19
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 5400,
      'dstOffset' => 0,
      'name' => 'SAST',
    ),
    1 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'SAST',
    ),
    2 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 3600,
      'name' => 'SAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2458173120,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -2109288600,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -860976000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -845254800,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -829526400,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -813805200,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => 7200,
    'startYear' => 1945,
  ),
  'name' => 'Africa/Johannesburg',
);

?>