<?php

/**
 * Data file for Africa/Banjul timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/10/2008 14:19:43
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -3996,
      'dstOffset' => 0,
      'name' => 'BMT',
    ),
    1 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
    2 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830380004,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1104533604,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -189385200,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1965,
  ),
  'name' => 'Africa/Banjul',
);

?>