<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2276643672,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WAT',
    'offset' => 3600,
    'startYear' => 1898,
  ),
  'name' => 'Africa/Kinshasa',
)
?>