<?php

/**
 * Data file for Africa/Dakar timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/06/2007 23:48:48
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
    1 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830379816,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -902098800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1942,
  ),
  'name' => 'Africa/Dakar',
);

?>