<?php

/**
 * Data file for Africa/Mogadishu timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/19/2008 17:06:40
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'EAT',
    ),
    1 => 
    array (
      'rawOffset' => 9000,
      'dstOffset' => 0,
      'name' => 'BEAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2403572488,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1230778800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -410236200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EAT',
    'offset' => 10800,
    'startYear' => 1957,
  ),
  'name' => 'Africa/Mogadishu',
);

?>