<?php

/**
 * Data file for Africa/El_Aaiun timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/29/2009 04:12:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
    1 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'WET',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1136070432,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 198291600,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WET',
    'offset' => 0,
    'startYear' => 1977,
  ),
  'name' => 'Africa/El_Aaiun',
);

?>