<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'SAST',
    ),
    1 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 3600,
      'name' => 'SAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2109289800,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -829526400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -813805200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SAST',
    'offset' => 7200,
    'startYear' => 1945,
  ),
  'name' => 'Africa/Maseru',
)
?>