<?php

/**
 * Data file for Africa/Sao_Tome timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/03/2007 22:43:51
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -2192,
      'dstOffset' => 0,
      'name' => 'LMT',
    ),
    1 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2713912016,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1830381808,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1913,
  ),
  'name' => 'Africa/Sao_Tome',
);

?>