<?php

/**
 * Data file for Africa/Luanda timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/03/2007 22:43:51
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 3124,
      'dstOffset' => 0,
      'name' => 'AOT',
    ),
    1 => 
    array (
      'rawOffset' => 3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2461452776,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1849395124,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WAT',
    'offset' => 3600,
    'startYear' => 1912,
  ),
  'name' => 'Africa/Luanda',
);

?>