<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2429827492,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1893,
  ),
  'name' => 'Africa/Lome',
)
?>