<?php

/**
 * Data file for Africa/Bamako timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/19/2008 17:06:40
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
    1 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830382080,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1131235200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -300841200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1961,
  ),
  'name' => 'Africa/Bamako',
);

?>