<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'SAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2109290664,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SAST',
    'offset' => 7200,
    'startYear' => 1904,
  ),
  'name' => 'Africa/Mbabane',
)
?>