<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
    1 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830379816,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -902098800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT',
    'offset' => 0,
    'startYear' => 1942,
  ),
  'name' => 'Africa/Dakar',
)
?>