<?php

/**
 * Data file for Africa/Maseru timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/26/2009 23:55:29
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'SAST',
    ),
    1 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 3600,
      'name' => 'SAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2109289800,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -829526400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -813805200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SAST',
    'offset' => 7200,
    'startYear' => 1945,
  ),
  'name' => 'Africa/Maseru',
);

?>