<?php

/**
 * Data file for Africa/Nairobi timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/19/2008 17:06:40
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'EAT',
    ),
    1 => 
    array (
      'rawOffset' => 9000,
      'dstOffset' => 0,
      'name' => 'BEAT',
    ),
    2 => 
    array (
      'rawOffset' => 9885,
      'dstOffset' => 0,
      'name' => 'BEAUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1309746436,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1262314800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -946780200,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -315629085,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EAT',
    'offset' => 10800,
    'startYear' => 1960,
  ),
  'name' => 'Africa/Nairobi',
);

?>