<?php

/**
 * Data file for Africa/Blantyre timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/06/2007 23:48:48
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'CAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2109291600,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CAT',
    'offset' => 7200,
    'startYear' => 1904,
  ),
  'name' => 'Africa/Blantyre',
);

?>