<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'EAT',
    ),
    1 => 
    array (
      'rawOffset' => 9885,
      'dstOffset' => 0,
      'name' => 'BEAUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1230777428,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -694321200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -284006685,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EAT',
    'offset' => 10800,
    'startYear' => 1961,
  ),
  'name' => 'Africa/Dar_es_Salaam',
)
?>