<?php

/**
 * Data file for Africa/Gaborone timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 07/21/2009 09:13:27
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 0,
      'name' => 'CAT',
    ),
    1 => 
    array (
      'rawOffset' => 7200,
      'dstOffset' => 3600,
      'name' => 'CAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2682294220,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -829526400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -813805200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CAT',
    'offset' => 7200,
    'startYear' => 1945,
  ),
  'name' => 'Africa/Gaborone',
);

?>