<?php

/**
 * Data file for Africa/Kampala timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/03/2007 18:13:14
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'EAT',
    ),
    1 => 
    array (
      'rawOffset' => 9000,
      'dstOffset' => 0,
      'name' => 'BEAT',
    ),
    2 => 
    array (
      'rawOffset' => 9885,
      'dstOffset' => 0,
      'name' => 'BEAUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1309745380,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1262314800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -694319400,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -410237085,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EAT',
    'offset' => 10800,
    'startYear' => 1957,
  ),
  'name' => 'Africa/Kampala',
);

?>