<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
    1 => 
    array (
      'rawOffset' => 0,
      'dstOffset' => 0,
      'name' => 'GMT',
    ),
    2 => 
    array (
      'rawOffset' => 3600,
      'dstOffset' => 0,
      'name' => 'WAT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1830384508,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1131231600,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -315619200,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WAT',
    'offset' => 3600,
    'startYear' => 1961,
  ),
  'name' => 'Africa/Niamey',
)
?>