<?php

/**
 * Data file for America/Bogota timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/03/2007 22:43:51
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -17780,
      'dstOffset' => 0,
      'name' => 'BMT',
    ),
    1 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'COT',
    ),
    2 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'COST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2707671820,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1739041420,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 704869200,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 733896000,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => -18000,
    'startYear' => 1994,
  ),
  'name' => 'America/Bogota',
);

?>