<?php

/**
 * Data file for America/Port_of_Spain timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/17/2009 13:26:25
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1825098836,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => -14400,
    'startYear' => 1913,
  ),
  'name' => 'America/Port_of_Spain',
);

?>