<?php

/**
 * Data file for America/Curacao timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  (c) Authors
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -16200,
      'dstOffset' => 0,
      'name' => 'ANT',
    ),
    1 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1826738656,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -157750200,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => -14400,
    'startYear' => 1966,
  ),
  'name' => 'America/Curacao',
);

?>