<?php

/**
 * Data file for America/Tegucigalpa timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/06/2007 23:48:48
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 0,
      'name' => 'CT',
    ),
    1 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 3600,
      'name' => 'CDT',
    ),
    2 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1538503868,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 547020000,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 559717200,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 578469600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 591166800,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 1146981600,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 1154926800,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => 1178431200,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 1186376400,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => 1209880800,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 1217826000,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => 1241330400,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => 1249275600,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => -21600,
    'startYear' => 2010,
  ),
  'name' => 'America/Tegucigalpa',
);

?>