<?php

/**
 * Data file for America/Caracas timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/19/2008 17:06:40
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -16060,
      'dstOffset' => 0,
      'name' => 'CMT',
    ),
    1 => 
    array (
      'rawOffset' => -16200,
      'dstOffset' => 0,
      'name' => 'VET',
    ),
    2 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'VET',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524505536,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1826739140,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -157750200,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 1197183600,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'VET',
    'offset' => -16200,
    'startYear' => 2008,
  ),
  'name' => 'America/Caracas',
);

?>