<?php

/**
 * Data file for America/St_Vincent timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/11/2009 10:31:33
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14696,
      'dstOffset' => 0,
      'name' => 'KMT',
    ),
    1 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524506904,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1830369304,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => -14400,
    'startYear' => 1913,
  ),
  'name' => 'America/St_Vincent',
);

?>