<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -16060,
      'dstOffset' => 0,
      'name' => 'CMT',
    ),
    1 => 
    array (
      'rawOffset' => -16200,
      'dstOffset' => 0,
      'name' => 'VET',
    ),
    2 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'VET',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524505536,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1826739140,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -157750200,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'VET',
    'offset' => -14400,
    'startYear' => 1966,
  ),
  'name' => 'America/Caracas',
)
?>