<?php

/**
 * Data file for America/Pangnirtung timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 02/21/2007 22:42:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AT',
    ),
    1 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'ADT',
    ),
    2 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
    3 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'AWT',
    ),
    4 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'APT',
    ),
    5 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 7200,
      'name' => 'ADDT',
    ),
    6 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'EST',
    ),
    7 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'EDT',
    ),
    8 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
    9 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 3600,
      'name' => 'CDT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2713894624,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1632074400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1615143600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -1596996000,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -1583182800,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -880221600,
      'type' => 3,
    ),
    6 => 
    array (
      'time' => -769395600,
      'type' => 4,
    ),
    7 => 
    array (
      'time' => -765399600,
      'type' => 2,
    ),
    8 => 
    array (
      'time' => -147902400,
      'type' => 5,
    ),
    9 => 
    array (
      'time' => -131572800,
      'type' => 2,
    ),
    10 => 
    array (
      'time' => 325663200,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 341384400,
      'type' => 2,
    ),
    12 => 
    array (
      'time' => 357112800,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 372834000,
      'type' => 2,
    ),
    14 => 
    array (
      'time' => 388562400,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 404888400,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 420012000,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 436338000,
      'type' => 2,
    ),
    18 => 
    array (
      'time' => 452066400,
      'type' => 1,
    ),
    19 => 
    array (
      'time' => 467787600,
      'type' => 2,
    ),
    20 => 
    array (
      'time' => 483516000,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 499237200,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 514965600,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 530686800,
      'type' => 2,
    ),
    24 => 
    array (
      'time' => 544600800,
      'type' => 1,
    ),
    25 => 
    array (
      'time' => 562136400,
      'type' => 2,
    ),
    26 => 
    array (
      'time' => 576050400,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 594190800,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 6.075E+8,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 625640400,
      'type' => 2,
    ),
    30 => 
    array (
      'time' => 638949600,
      'type' => 1,
    ),
    31 => 
    array (
      'time' => 657090000,
      'type' => 2,
    ),
    32 => 
    array (
      'time' => 671004000,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 688539600,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 702453600,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 719989200,
      'type' => 2,
    ),
    36 => 
    array (
      'time' => 733903200,
      'type' => 1,
    ),
    37 => 
    array (
      'time' => 752043600,
      'type' => 2,
    ),
    38 => 
    array (
      'time' => 765352800,
      'type' => 1,
    ),
    39 => 
    array (
      'time' => 783493200,
      'type' => 2,
    ),
    40 => 
    array (
      'time' => 796708800,
      'type' => 6,
    ),
    41 => 
    array (
      'time' => 796806000,
      'type' => 7,
    ),
    42 => 
    array (
      'time' => 814946400,
      'type' => 6,
    ),
    43 => 
    array (
      'time' => 828860400,
      'type' => 7,
    ),
    44 => 
    array (
      'time' => 846396000,
      'type' => 6,
    ),
    45 => 
    array (
      'time' => 860310000,
      'type' => 7,
    ),
    46 => 
    array (
      'time' => 877845600,
      'type' => 6,
    ),
    47 => 
    array (
      'time' => 891759600,
      'type' => 7,
    ),
    48 => 
    array (
      'time' => 909295200,
      'type' => 6,
    ),
    49 => 
    array (
      'time' => 923209200,
      'type' => 7,
    ),
    50 => 
    array (
      'time' => 941349600,
      'type' => 6,
    ),
    51 => 
    array (
      'time' => 941353200,
      'type' => 8,
    ),
    52 => 
    array (
      'time' => 954662400,
      'type' => 9,
    ),
    53 => 
    array (
      'time' => 972802800,
      'type' => 8,
    ),
    54 => 
    array (
      'time' => 972806400,
      'type' => 6,
    ),
    55 => 
    array (
      'time' => 986108400,
      'type' => 7,
    ),
    56 => 
    array (
      'time' => 1004248800,
      'type' => 6,
    ),
    57 => 
    array (
      'time' => 1018162800,
      'type' => 7,
    ),
    58 => 
    array (
      'time' => 1035698400,
      'type' => 6,
    ),
    59 => 
    array (
      'time' => 1049612400,
      'type' => 7,
    ),
    60 => 
    array (
      'time' => 1067148000,
      'type' => 6,
    ),
    61 => 
    array (
      'time' => 1081062000,
      'type' => 7,
    ),
    62 => 
    array (
      'time' => 1099202400,
      'type' => 6,
    ),
    63 => 
    array (
      'time' => 1112511600,
      'type' => 7,
    ),
    64 => 
    array (
      'time' => 1130652000,
      'type' => 6,
    ),
    65 => 
    array (
      'time' => 1143961200,
      'type' => 7,
    ),
    66 => 
    array (
      'time' => 1162101600,
      'type' => 6,
    ),
    67 => 
    array (
      'time' => 1173596400,
      'type' => 7,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => -18000,
    'name' => 'E%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 2,
      'date' => '8',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'end' => 
    array (
      'month' => 10,
      'date' => '1',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'startYear' => 2008,
  ),
  'name' => 'America/Pangnirtung',
);

?>