<?php

/**
 * Data file for America/Iqaluit timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/06/2007 23:48:48
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'ET',
    ),
    1 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'EDT',
    ),
    2 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'EST',
    ),
    3 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'EWT',
    ),
    4 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'EPT',
    ),
    5 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 7200,
      'name' => 'EDDT',
    ),
    6 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
    7 => 
    array (
      'rawOffset' => -21600,
      'dstOffset' => 3600,
      'name' => 'CDT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2713893968,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1632070800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1615140000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -1596992400,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -1583179200,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -880218000,
      'type' => 3,
    ),
    6 => 
    array (
      'time' => -769395600,
      'type' => 4,
    ),
    7 => 
    array (
      'time' => -765396000,
      'type' => 2,
    ),
    8 => 
    array (
      'time' => -147898800,
      'type' => 5,
    ),
    9 => 
    array (
      'time' => -131569200,
      'type' => 2,
    ),
    10 => 
    array (
      'time' => 325666800,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 341388000,
      'type' => 2,
    ),
    12 => 
    array (
      'time' => 357116400,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 372837600,
      'type' => 2,
    ),
    14 => 
    array (
      'time' => 388566000,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 404892000,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 420015600,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 436341600,
      'type' => 2,
    ),
    18 => 
    array (
      'time' => 452070000,
      'type' => 1,
    ),
    19 => 
    array (
      'time' => 467791200,
      'type' => 2,
    ),
    20 => 
    array (
      'time' => 483519600,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 499240800,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 514969200,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 530690400,
      'type' => 2,
    ),
    24 => 
    array (
      'time' => 544604400,
      'type' => 1,
    ),
    25 => 
    array (
      'time' => 562140000,
      'type' => 2,
    ),
    26 => 
    array (
      'time' => 576054000,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 594194400,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 607503600,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 625644000,
      'type' => 2,
    ),
    30 => 
    array (
      'time' => 638953200,
      'type' => 1,
    ),
    31 => 
    array (
      'time' => 657093600,
      'type' => 2,
    ),
    32 => 
    array (
      'time' => 671007600,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 688543200,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 702457200,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 719992800,
      'type' => 2,
    ),
    36 => 
    array (
      'time' => 733906800,
      'type' => 1,
    ),
    37 => 
    array (
      'time' => 752047200,
      'type' => 2,
    ),
    38 => 
    array (
      'time' => 765356400,
      'type' => 1,
    ),
    39 => 
    array (
      'time' => 783496800,
      'type' => 2,
    ),
    40 => 
    array (
      'time' => 796806000,
      'type' => 1,
    ),
    41 => 
    array (
      'time' => 814946400,
      'type' => 2,
    ),
    42 => 
    array (
      'time' => 828860400,
      'type' => 1,
    ),
    43 => 
    array (
      'time' => 846396000,
      'type' => 2,
    ),
    44 => 
    array (
      'time' => 860310000,
      'type' => 1,
    ),
    45 => 
    array (
      'time' => 877845600,
      'type' => 2,
    ),
    46 => 
    array (
      'time' => 891759600,
      'type' => 1,
    ),
    47 => 
    array (
      'time' => 909295200,
      'type' => 2,
    ),
    48 => 
    array (
      'time' => 923209200,
      'type' => 1,
    ),
    49 => 
    array (
      'time' => 941349600,
      'type' => 2,
    ),
    50 => 
    array (
      'time' => 941353200,
      'type' => 6,
    ),
    51 => 
    array (
      'time' => 954662400,
      'type' => 7,
    ),
    52 => 
    array (
      'time' => 972802800,
      'type' => 6,
    ),
    53 => 
    array (
      'time' => 972806400,
      'type' => 2,
    ),
    54 => 
    array (
      'time' => 986108400,
      'type' => 1,
    ),
    55 => 
    array (
      'time' => 1004248800,
      'type' => 2,
    ),
    56 => 
    array (
      'time' => 1018162800,
      'type' => 1,
    ),
    57 => 
    array (
      'time' => 1035698400,
      'type' => 2,
    ),
    58 => 
    array (
      'time' => 1049612400,
      'type' => 1,
    ),
    59 => 
    array (
      'time' => 1067148000,
      'type' => 2,
    ),
    60 => 
    array (
      'time' => 1081062000,
      'type' => 1,
    ),
    61 => 
    array (
      'time' => 1099202400,
      'type' => 2,
    ),
    62 => 
    array (
      'time' => 1112511600,
      'type' => 1,
    ),
    63 => 
    array (
      'time' => 1130652000,
      'type' => 2,
    ),
    64 => 
    array (
      'time' => 1143961200,
      'type' => 1,
    ),
    65 => 
    array (
      'time' => 1162101600,
      'type' => 2,
    ),
    66 => 
    array (
      'time' => 1173596400,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => -18000,
    'name' => 'E%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 2,
      'date' => '8',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'end' => 
    array (
      'month' => 10,
      'date' => '1',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'startYear' => 2008,
  ),
  'name' => 'America/Iqaluit',
);

?>