<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'GFT',
    ),
    1 => 
    array (
      'rawOffset' => -10800,
      'dstOffset' => 0,
      'name' => 'GFT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1846269040,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -71092800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GFT',
    'offset' => -10800,
    'startYear' => 1968,
  ),
  'name' => 'America/Cayenne',
)
?>