<?php

/**
 * Data file for America/Blanc-Sablon timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 01/01/2008 04:45:33
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AT',
    ),
    1 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'ADT',
    ),
    2 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
    3 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'AWT',
    ),
    4 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'APT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2713896692,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1632074400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1614798000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -880221600,
      'type' => 3,
    ),
    4 => 
    array (
      'time' => -769395600,
      'type' => 4,
    ),
    5 => 
    array (
      'time' => -765399600,
      'type' => 2,
    ),
    6 => 
    array (
      'time' => 14400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => -14400,
    'startYear' => 1971,
  ),
  'name' => 'America/Blanc-Sablon',
);

?>