<?php

/**
 * Data file for America/Santiago timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -16960,
      'dstOffset' => 0,
      'name' => 'SMT',
    ),
    1 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'CLT',
    ),
    2 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 3600,
      'name' => 'CLST',
    ),
    3 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'CLT',
    ),
    4 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'CLST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524504640,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1893439040,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1619982000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -1593720000,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -1335985200,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -1317585600,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -1304362800,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => -1286049600,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => -1272826800,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => -1254513600,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => -1241290800,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => -1222977600,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => -1209754800,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => -1191355200,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => -1178132400,
      'type' => 3,
    ),
    15 => 
    array (
      'time' => -101937600,
      'type' => 4,
    ),
    16 => 
    array (
      'time' => -88635600,
      'type' => 3,
    ),
    17 => 
    array (
      'time' => -69886800,
      'type' => 4,
    ),
    18 => 
    array (
      'time' => -57186000,
      'type' => 3,
    ),
    19 => 
    array (
      'time' => -38437200,
      'type' => 4,
    ),
    20 => 
    array (
      'time' => -25736400,
      'type' => 3,
    ),
    21 => 
    array (
      'time' => -6987600,
      'type' => 4,
    ),
    22 => 
    array (
      'time' => 6318000,
      'type' => 3,
    ),
    23 => 
    array (
      'time' => 24462000,
      'type' => 4,
    ),
    24 => 
    array (
      'time' => 37767600,
      'type' => 3,
    ),
    25 => 
    array (
      'time' => 55911600,
      'type' => 4,
    ),
    26 => 
    array (
      'time' => 69217200,
      'type' => 3,
    ),
    27 => 
    array (
      'time' => 87966000,
      'type' => 4,
    ),
    28 => 
    array (
      'time' => 100666800,
      'type' => 3,
    ),
    29 => 
    array (
      'time' => 119415600,
      'type' => 4,
    ),
    30 => 
    array (
      'time' => 132116400,
      'type' => 3,
    ),
    31 => 
    array (
      'time' => 150865200,
      'type' => 4,
    ),
    32 => 
    array (
      'time' => 163566000,
      'type' => 3,
    ),
    33 => 
    array (
      'time' => 182314800,
      'type' => 4,
    ),
    34 => 
    array (
      'time' => 195620400,
      'type' => 3,
    ),
    35 => 
    array (
      'time' => 213764400,
      'type' => 4,
    ),
    36 => 
    array (
      'time' => 227070000,
      'type' => 3,
    ),
    37 => 
    array (
      'time' => 245214000,
      'type' => 4,
    ),
    38 => 
    array (
      'time' => 258519600,
      'type' => 3,
    ),
    39 => 
    array (
      'time' => 277268400,
      'type' => 4,
    ),
    40 => 
    array (
      'time' => 289969200,
      'type' => 3,
    ),
    41 => 
    array (
      'time' => 308718000,
      'type' => 4,
    ),
    42 => 
    array (
      'time' => 321418800,
      'type' => 3,
    ),
    43 => 
    array (
      'time' => 340167600,
      'type' => 4,
    ),
    44 => 
    array (
      'time' => 353473200,
      'type' => 3,
    ),
    45 => 
    array (
      'time' => 371617200,
      'type' => 4,
    ),
    46 => 
    array (
      'time' => 384922800,
      'type' => 3,
    ),
    47 => 
    array (
      'time' => 403066800,
      'type' => 4,
    ),
    48 => 
    array (
      'time' => 416372400,
      'type' => 3,
    ),
    49 => 
    array (
      'time' => 434516400,
      'type' => 4,
    ),
    50 => 
    array (
      'time' => 447822000,
      'type' => 3,
    ),
    51 => 
    array (
      'time' => 466570800,
      'type' => 4,
    ),
    52 => 
    array (
      'time' => 479271600,
      'type' => 3,
    ),
    53 => 
    array (
      'time' => 498020400,
      'type' => 4,
    ),
    54 => 
    array (
      'time' => 510721200,
      'type' => 3,
    ),
    55 => 
    array (
      'time' => 529470000,
      'type' => 4,
    ),
    56 => 
    array (
      'time' => 542775600,
      'type' => 3,
    ),
    57 => 
    array (
      'time' => 560919600,
      'type' => 4,
    ),
    58 => 
    array (
      'time' => 574225200,
      'type' => 3,
    ),
    59 => 
    array (
      'time' => 592369200,
      'type' => 4,
    ),
    60 => 
    array (
      'time' => 605674800,
      'type' => 3,
    ),
    61 => 
    array (
      'time' => 624423600,
      'type' => 4,
    ),
    62 => 
    array (
      'time' => 637124400,
      'type' => 3,
    ),
    63 => 
    array (
      'time' => 655873200,
      'type' => 4,
    ),
    64 => 
    array (
      'time' => 668574000,
      'type' => 3,
    ),
    65 => 
    array (
      'time' => 687322800,
      'type' => 4,
    ),
    66 => 
    array (
      'time' => 700628400,
      'type' => 3,
    ),
    67 => 
    array (
      'time' => 718772400,
      'type' => 4,
    ),
    68 => 
    array (
      'time' => 732078000,
      'type' => 3,
    ),
    69 => 
    array (
      'time' => 750222000,
      'type' => 4,
    ),
    70 => 
    array (
      'time' => 763527600,
      'type' => 3,
    ),
    71 => 
    array (
      'time' => 781671600,
      'type' => 4,
    ),
    72 => 
    array (
      'time' => 794977200,
      'type' => 3,
    ),
    73 => 
    array (
      'time' => 813726000,
      'type' => 4,
    ),
    74 => 
    array (
      'time' => 826426800,
      'type' => 3,
    ),
    75 => 
    array (
      'time' => 845175600,
      'type' => 4,
    ),
    76 => 
    array (
      'time' => 857876400,
      'type' => 3,
    ),
    77 => 
    array (
      'time' => 876625200,
      'type' => 4,
    ),
    78 => 
    array (
      'time' => 889934400,
      'type' => 3,
    ),
    79 => 
    array (
      'time' => 906868800,
      'type' => 4,
    ),
    80 => 
    array (
      'time' => 923194800,
      'type' => 3,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => -14400,
    'name' => 'CL%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 9,
      'date' => '9',
      'day_of_week' => -1,
      'time' => 1.44E+7,
      'type' => 2,
    ),
    'end' => 
    array (
      'month' => 2,
      'date' => '9',
      'day_of_week' => -1,
      'time' => 1.08E+7,
      'type' => 2,
    ),
    'startYear' => 2000,
  ),
  'name' => 'America/Santiago',
);

?>