<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -18840,
      'dstOffset' => 0,
      'name' => 'QMT',
    ),
    1 => 
    array (
      'rawOffset' => -18000,
      'dstOffset' => 0,
      'name' => 'ECT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524502440,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1230749160,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'ECT',
    'offset' => -18000,
    'startYear' => 1932,
  ),
  'name' => 'America/Guayaquil',
)
?>