<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'WST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -31536000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WST',
    'offset' => 28800,
    'startYear' => 1970,
  ),
  'name' => 'Antarctica/Casey',
)
?>