<?php

/**
 * Data file for Antarctica/Mawson timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/15/2009 15:47:05
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'MAWT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -501206400,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'MAWT',
    'offset' => 21600,
    'startYear' => 1955,
  ),
  'name' => 'Antarctica/Mawson',
);

?>