<?php

/**
 * Data file for Antarctica/Casey timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 07/21/2009 09:13:27
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'WST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -31536000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WST',
    'offset' => 28800,
    'startYear' => 1970,
  ),
  'name' => 'Antarctica/Casey',
);

?>