<?php

/**
 * Data file for Antarctica/Palmer timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'ARST',
    ),
    1 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'ART',
    ),
    2 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'ARST',
    ),
    3 => 
    array (
      'rawOffset' => -10800,
      'dstOffset' => 0,
      'name' => 'ART',
    ),
    4 => 
    array (
      'rawOffset' => -10800,
      'dstOffset' => 3600,
      'name' => 'ARST',
    ),
    5 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 0,
      'name' => 'CLT',
    ),
    6 => 
    array (
      'rawOffset' => -14400,
      'dstOffset' => 3600,
      'name' => 'CLST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -157766400,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -152658000,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -132955200,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -121122000,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -101419200,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -86907600,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -71092800,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => -54766800,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => -39038400,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => -23317200,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => -7588800,
      'type' => 3,
    ),
    11 => 
    array (
      'time' => 128142000,
      'type' => 4,
    ),
    12 => 
    array (
      'time' => 136605600,
      'type' => 3,
    ),
    13 => 
    array (
      'time' => 150260400,
      'type' => 4,
    ),
    14 => 
    array (
      'time' => 165981600,
      'type' => 3,
    ),
    15 => 
    array (
      'time' => 181710000,
      'type' => 4,
    ),
    16 => 
    array (
      'time' => 197431200,
      'type' => 3,
    ),
    17 => 
    array (
      'time' => 213159600,
      'type' => 4,
    ),
    18 => 
    array (
      'time' => 228880800,
      'type' => 3,
    ),
    19 => 
    array (
      'time' => 389070000,
      'type' => 5,
    ),
    20 => 
    array (
      'time' => 403070400,
      'type' => 6,
    ),
    21 => 
    array (
      'time' => 416372400,
      'type' => 5,
    ),
    22 => 
    array (
      'time' => 434520000,
      'type' => 6,
    ),
    23 => 
    array (
      'time' => 447822000,
      'type' => 5,
    ),
    24 => 
    array (
      'time' => 466574400,
      'type' => 6,
    ),
    25 => 
    array (
      'time' => 479271600,
      'type' => 5,
    ),
    26 => 
    array (
      'time' => 498024000,
      'type' => 6,
    ),
    27 => 
    array (
      'time' => 510721200,
      'type' => 5,
    ),
    28 => 
    array (
      'time' => 529473600,
      'type' => 6,
    ),
    29 => 
    array (
      'time' => 542775600,
      'type' => 5,
    ),
    30 => 
    array (
      'time' => 560923200,
      'type' => 6,
    ),
    31 => 
    array (
      'time' => 574225200,
      'type' => 5,
    ),
    32 => 
    array (
      'time' => 592372800,
      'type' => 6,
    ),
    33 => 
    array (
      'time' => 605674800,
      'type' => 5,
    ),
    34 => 
    array (
      'time' => 624427200,
      'type' => 6,
    ),
    35 => 
    array (
      'time' => 637124400,
      'type' => 5,
    ),
    36 => 
    array (
      'time' => 655876800,
      'type' => 6,
    ),
    37 => 
    array (
      'time' => 668574000,
      'type' => 5,
    ),
    38 => 
    array (
      'time' => 687326400,
      'type' => 6,
    ),
    39 => 
    array (
      'time' => 700628400,
      'type' => 5,
    ),
    40 => 
    array (
      'time' => 718776000,
      'type' => 6,
    ),
    41 => 
    array (
      'time' => 732078000,
      'type' => 5,
    ),
    42 => 
    array (
      'time' => 750225600,
      'type' => 6,
    ),
    43 => 
    array (
      'time' => 763527600,
      'type' => 5,
    ),
    44 => 
    array (
      'time' => 781675200,
      'type' => 6,
    ),
    45 => 
    array (
      'time' => 794977200,
      'type' => 5,
    ),
    46 => 
    array (
      'time' => 813729600,
      'type' => 6,
    ),
    47 => 
    array (
      'time' => 826426800,
      'type' => 5,
    ),
    48 => 
    array (
      'time' => 845179200,
      'type' => 6,
    ),
    49 => 
    array (
      'time' => 857876400,
      'type' => 5,
    ),
    50 => 
    array (
      'time' => 876628800,
      'type' => 6,
    ),
    51 => 
    array (
      'time' => 889930800,
      'type' => 5,
    ),
    52 => 
    array (
      'time' => 906868800,
      'type' => 6,
    ),
    53 => 
    array (
      'time' => 923194800,
      'type' => 5,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => -14400,
    'name' => 'CL%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 9,
      'date' => '9',
      'day_of_week' => -1,
      'time' => 0,
      'type' => 0,
    ),
    'end' => 
    array (
      'month' => 2,
      'date' => '9',
      'day_of_week' => -1,
      'time' => 0,
      'type' => 0,
    ),
    'startYear' => 2000,
  ),
  'name' => 'Antarctica/Palmer',
);

?>