<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'NZT',
    ),
    1 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 3600,
      'name' => 'NZDT',
    ),
    2 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'NZST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -441849600,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 152632800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 162309600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 183477600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 194968800,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 215532000,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 226418400,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => 244562400,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 246981600,
      'type' => 1,
    ),
    9 => 
    array (
      'time' => 257868000,
      'type' => 2,
    ),
    10 => 
    array (
      'time' => 276012000,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 278431200,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => 289317600,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => 308066400,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => 309880800,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 320767200,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 339516000,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 341330400,
      'type' => 1,
    ),
    18 => 
    array (
      'time' => 352216800,
      'type' => 2,
    ),
    19 => 
    array (
      'time' => 370965600,
      'type' => 1,
    ),
    20 => 
    array (
      'time' => 372780000,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 384271200,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 402415200,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 404834400,
      'type' => 1,
    ),
    24 => 
    array (
      'time' => 415720800,
      'type' => 2,
    ),
    25 => 
    array (
      'time' => 433864800,
      'type' => 1,
    ),
    26 => 
    array (
      'time' => 436284000,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 447170400,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 465919200,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 467733600,
      'type' => 1,
    ),
    30 => 
    array (
      'time' => 478620000,
      'type' => 2,
    ),
    31 => 
    array (
      'time' => 497368800,
      'type' => 1,
    ),
    32 => 
    array (
      'time' => 499183200,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 510069600,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 528818400,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 530632800,
      'type' => 1,
    ),
    36 => 
    array (
      'time' => 541519200,
      'type' => 2,
    ),
    37 => 
    array (
      'time' => 560268000,
      'type' => 1,
    ),
    38 => 
    array (
      'time' => 562082400,
      'type' => 1,
    ),
    39 => 
    array (
      'time' => 573573600,
      'type' => 2,
    ),
    40 => 
    array (
      'time' => 591717600,
      'type' => 1,
    ),
    41 => 
    array (
      'time' => 594136800,
      'type' => 1,
    ),
    42 => 
    array (
      'time' => 605023200,
      'type' => 2,
    ),
    43 => 
    array (
      'time' => 623167200,
      'type' => 1,
    ),
    44 => 
    array (
      'time' => 623772000,
      'type' => 1,
    ),
    45 => 
    array (
      'time' => 637682400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 43200,
    'name' => 'NZ%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 9,
      'date' => '1',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'end' => 
    array (
      'month' => 2,
      'date' => '15',
      'day_of_week' => -1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'startYear' => 1991,
  ),
  'name' => 'Antarctica/McMurdo',
)
?>