<?php

/**
 * Data file for Asia/Makassar timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/03/2007 18:13:14
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 28656,
      'dstOffset' => 0,
      'name' => 'MMT',
    ),
    1 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'CIT',
    ),
    2 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'JST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1577951856,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1172908656,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -880272000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -766054800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CIT',
    'offset' => 28800,
    'startYear' => 1946,
  ),
  'name' => 'Asia/Makassar',
);

?>