<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'ULAT',
    ),
    1 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'ULAT',
    ),
    2 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 3600,
      'name' => 'ULAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2032931252,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 252435600,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 417974400,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 433782000,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 448992000,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 449593200,
      'type' => 2,
    ),
    6 => 
    array (
      'time' => 465318000,
      'type' => 1,
    ),
    7 => 
    array (
      'time' => 481046400,
      'type' => 2,
    ),
    8 => 
    array (
      'time' => 496767600,
      'type' => 1,
    ),
    9 => 
    array (
      'time' => 512496000,
      'type' => 2,
    ),
    10 => 
    array (
      'time' => 528217200,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 543945600,
      'type' => 2,
    ),
    12 => 
    array (
      'time' => 559666800,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 575395200,
      'type' => 2,
    ),
    14 => 
    array (
      'time' => 591116400,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 606844800,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 622566000,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 638294400,
      'type' => 2,
    ),
    18 => 
    array (
      'time' => 654620400,
      'type' => 1,
    ),
    19 => 
    array (
      'time' => 670348800,
      'type' => 2,
    ),
    20 => 
    array (
      'time' => 686070000,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 701798400,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 717519600,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 733248000,
      'type' => 2,
    ),
    24 => 
    array (
      'time' => 748969200,
      'type' => 1,
    ),
    25 => 
    array (
      'time' => 764697600,
      'type' => 2,
    ),
    26 => 
    array (
      'time' => 780418800,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 796147200,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 811868400,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 828201600,
      'type' => 2,
    ),
    30 => 
    array (
      'time' => 843922800,
      'type' => 1,
    ),
    31 => 
    array (
      'time' => 859651200,
      'type' => 2,
    ),
    32 => 
    array (
      'time' => 875372400,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 891100800,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 906822000,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 988394400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 28800,
    'name' => 'ULA%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 2,
      'date' => -1,
      'day_of_week' => 7,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'end' => 
    array (
      'month' => 8,
      'date' => -1,
      'day_of_week' => 7,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'startYear' => 2002,
  ),
  'name' => 'Asia/Ulaanbaatar',
)
?>