<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 12344,
      'dstOffset' => 0,
      'name' => 'TMT',
    ),
    1 => 
    array (
      'rawOffset' => 12600,
      'dstOffset' => 0,
      'name' => 'IRST',
    ),
    2 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'IRT',
    ),
    3 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 3600,
      'name' => 'IRDT',
    ),
    4 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'IRST',
    ),
    5 => 
    array (
      'rawOffset' => 12600,
      'dstOffset' => 3600,
      'name' => 'IRDT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1704165944,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -757394744,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 247177800,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 259272000,
      'type' => 3,
    ),
    4 => 
    array (
      'time' => 277758000,
      'type' => 4,
    ),
    5 => 
    array (
      'time' => 283982400,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 290809800,
      'type' => 5,
    ),
    7 => 
    array (
      'time' => 306531000,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 322432200,
      'type' => 5,
    ),
    9 => 
    array (
      'time' => 338499000,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 669587400,
      'type' => 5,
    ),
    11 => 
    array (
      'time' => 673212600,
      'type' => 5,
    ),
    12 => 
    array (
      'time' => 685481400,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 701209800,
      'type' => 5,
    ),
    14 => 
    array (
      'time' => 717103800,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 732745800,
      'type' => 5,
    ),
    16 => 
    array (
      'time' => 748639800,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 764281800,
      'type' => 5,
    ),
    18 => 
    array (
      'time' => 780175800,
      'type' => 1,
    ),
    19 => 
    array (
      'time' => 795817800,
      'type' => 5,
    ),
    20 => 
    array (
      'time' => 811711800,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 827353800,
      'type' => 5,
    ),
    22 => 
    array (
      'time' => 843247800,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 858976200,
      'type' => 5,
    ),
    24 => 
    array (
      'time' => 874870200,
      'type' => 1,
    ),
    25 => 
    array (
      'time' => 890512200,
      'type' => 5,
    ),
    26 => 
    array (
      'time' => 906406200,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 922048200,
      'type' => 5,
    ),
    28 => 
    array (
      'time' => 937942200,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 953584200,
      'type' => 5,
    ),
    30 => 
    array (
      'time' => 969478200,
      'type' => 1,
    ),
    31 => 
    array (
      'time' => 985206600,
      'type' => 5,
    ),
    32 => 
    array (
      'time' => 1001100600,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 1016742600,
      'type' => 5,
    ),
    34 => 
    array (
      'time' => 1032636600,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 1048278600,
      'type' => 5,
    ),
    36 => 
    array (
      'time' => 1064172600,
      'type' => 1,
    ),
    37 => 
    array (
      'time' => 1079814600,
      'type' => 5,
    ),
    38 => 
    array (
      'time' => 1095708600,
      'type' => 1,
    ),
    39 => 
    array (
      'time' => 1111437000,
      'type' => 5,
    ),
    40 => 
    array (
      'time' => 1127331000,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => 12600,
    'startYear' => 2006,
  ),
  'name' => 'Asia/Tehran',
)
?>