<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'EIT',
    ),
    1 => 
    array (
      'rawOffset' => 34200,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1172913768,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -820573200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -189423000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EIT',
    'offset' => 32400,
    'startYear' => 1964,
  ),
  'name' => 'Asia/Jayapura',
)
?>