<?php

/**
 * Data file for Asia/Hovd timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 02/21/2007 22:42:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'HOVT',
    ),
    1 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'HOVT',
    ),
    2 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 3600,
      'name' => 'HOVST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2032927596,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 252439200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 417978000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 433785600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 448995600,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 449596800,
      'type' => 2,
    ),
    6 => 
    array (
      'time' => 465321600,
      'type' => 1,
    ),
    7 => 
    array (
      'time' => 481050000,
      'type' => 2,
    ),
    8 => 
    array (
      'time' => 496771200,
      'type' => 1,
    ),
    9 => 
    array (
      'time' => 512499600,
      'type' => 2,
    ),
    10 => 
    array (
      'time' => 528220800,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 543949200,
      'type' => 2,
    ),
    12 => 
    array (
      'time' => 559670400,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 575398800,
      'type' => 2,
    ),
    14 => 
    array (
      'time' => 591120000,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 606848400,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 622569600,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 638298000,
      'type' => 2,
    ),
    18 => 
    array (
      'time' => 654624000,
      'type' => 1,
    ),
    19 => 
    array (
      'time' => 670352400,
      'type' => 2,
    ),
    20 => 
    array (
      'time' => 686073600,
      'type' => 1,
    ),
    21 => 
    array (
      'time' => 701802000,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 717523200,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 733251600,
      'type' => 2,
    ),
    24 => 
    array (
      'time' => 748972800,
      'type' => 1,
    ),
    25 => 
    array (
      'time' => 764701200,
      'type' => 2,
    ),
    26 => 
    array (
      'time' => 780422400,
      'type' => 1,
    ),
    27 => 
    array (
      'time' => 796150800,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 811872000,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 828205200,
      'type' => 2,
    ),
    30 => 
    array (
      'time' => 843926400,
      'type' => 1,
    ),
    31 => 
    array (
      'time' => 859654800,
      'type' => 2,
    ),
    32 => 
    array (
      'time' => 875376000,
      'type' => 1,
    ),
    33 => 
    array (
      'time' => 891104400,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 906825600,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 988398000,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 25200,
    'name' => 'HOV%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 2,
      'date' => -1,
      'day_of_week' => 7,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'end' => 
    array (
      'month' => 8,
      'date' => -1,
      'day_of_week' => 7,
      'time' => 7.2E+6,
      'type' => 0,
    ),
    'startYear' => 2002,
  ),
  'name' => 'Asia/Hovd',
);

?>