<?php

/**
 * Data file for Asia/Bangkok timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/17/2009 13:26:25
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 24124,
      'dstOffset' => 0,
      'name' => 'BMT',
    ),
    1 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'ICT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2840164924,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1570084924,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'ICT',
    'offset' => 25200,
    'startYear' => 1921,
  ),
  'name' => 'Asia/Bangkok',
);

?>