<?php

/**
 * Data file for Asia/Kuching timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 27000,
      'dstOffset' => 0,
      'name' => 'BORT',
    ),
    1 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'BORT',
    ),
    2 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 1200,
      'name' => 'BORTST',
    ),
    3 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'JST',
    ),
    4 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'MYT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1383463280,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1167636600,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1082448000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -1074586800,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -1050825600,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -1042964400,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -1019289600,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => -1011428400,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => -987753600,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => -979892400,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => -956217600,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => -948356400,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => -924595200,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => -916734000,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => -893059200,
      'type' => 2,
    ),
    15 => 
    array (
      'time' => -885198000,
      'type' => 1,
    ),
    16 => 
    array (
      'time' => -879667200,
      'type' => 3,
    ),
    17 => 
    array (
      'time' => -767005200,
      'type' => 1,
    ),
    18 => 
    array (
      'time' => 378662400,
      'type' => 4,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'MYT',
    'offset' => 28800,
    'startYear' => 1982,
  ),
  'name' => 'Asia/Kuching',
);

?>