<?php

/**
 * Data file for Asia/Dubai timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/06/2007 23:48:48
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'GST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1577936472,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GST',
    'offset' => 14400,
    'startYear' => 1920,
  ),
  'name' => 'Asia/Dubai',
);

?>