<?php

/**
 * Data file for Asia/Dhaka timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/05/2009 16:44:34
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 21200,
      'dstOffset' => 0,
      'name' => 'HMT',
    ),
    1 => 
    array (
      'rawOffset' => 23400,
      'dstOffset' => 0,
      'name' => 'BURT',
    ),
    2 => 
    array (
      'rawOffset' => 19800,
      'dstOffset' => 0,
      'name' => 'IST',
    ),
    3 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'DACT',
    ),
    4 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'BDT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524543300,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -891582800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -872058600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -862637400,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -576138600,
      'type' => 3,
    ),
    5 => 
    array (
      'time' => 38772000,
      'type' => 4,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'BDT',
    'offset' => 21600,
    'startYear' => 1972,
  ),
  'name' => 'Asia/Dhaka',
);

?>