<?php

/**
 * Data file for Asia/Thimphu timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/19/2009 20:43:28
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 19800,
      'dstOffset' => 0,
      'name' => 'IST',
    ),
    1 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'BTT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -706341516,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 560025000,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'BTT',
    'offset' => 21600,
    'startYear' => 1988,
  ),
  'name' => 'Asia/Thimphu',
);

?>