<?php

/**
 * Data file for Asia/Jayapura timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'EIT',
    ),
    1 => 
    array (
      'rawOffset' => 34200,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1172913768,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -820573200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -189423000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'EIT',
    'offset' => 32400,
    'startYear' => 1964,
  ),
  'name' => 'Asia/Jayapura',
);

?>