<?php

/**
 * Data file for Asia/Kuwait timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/03/2007 18:13:14
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -631163516,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AST',
    'offset' => 10800,
    'startYear' => 1950,
  ),
  'name' => 'Asia/Kuwait',
);

?>