<?php

/**
 * Data file for Asia/Pontianak timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/13/2009 16:13:10
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 26240,
      'dstOffset' => 0,
      'name' => 'PMT',
    ),
    1 => 
    array (
      'rawOffset' => 27000,
      'dstOffset' => 0,
      'name' => 'WIT',
    ),
    2 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'JST',
    ),
    3 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'WIT',
    ),
    4 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'CIT',
    ),
    5 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'WIT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1946186240,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1172906240,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -881220600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -766054800,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -683883000,
      'type' => 3,
    ),
    5 => 
    array (
      'time' => -620812800,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -189415800,
      'type' => 4,
    ),
    7 => 
    array (
      'time' => 567964800,
      'type' => 5,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WIT',
    'offset' => 25200,
    'startYear' => 1988,
  ),
  'name' => 'Asia/Pontianak',
);

?>