<?php

/**
 * Data file for Asia/Kabul timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  (c) Authors
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'AFT',
    ),
    1 => 
    array (
      'rawOffset' => 16200,
      'dstOffset' => 0,
      'name' => 'AFT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524538208,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -788932800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'AFT',
    'offset' => 16200,
    'startYear' => 1945,
  ),
  'name' => 'Asia/Kabul',
);

?>