<?php

/**
 * Data file for Asia/Brunei timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/17/2009 13:26:25
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 27000,
      'dstOffset' => 0,
      'name' => 'BNT',
    ),
    1 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'BNT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1383464380,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1167636600,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'BNT',
    'offset' => 28800,
    'startYear' => 1933,
  ),
  'name' => 'Asia/Brunei',
);

?>