<?php

/**
 * Data file for Asia/Novosibirsk timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'NOVT',
    ),
    1 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'NOVT',
    ),
    2 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 3600,
      'name' => 'NOVST',
    ),
    3 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 3600,
      'name' => 'NOVST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1579476700,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1247551200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 354906000,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 370713600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 386442000,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 402249600,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 417978000,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => 433785600,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 449607600,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => 465332400,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 481057200,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => 496782000,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => 512506800,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => 528231600,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => 543956400,
      'type' => 2,
    ),
    15 => 
    array (
      'time' => 559681200,
      'type' => 1,
    ),
    16 => 
    array (
      'time' => 575406000,
      'type' => 2,
    ),
    17 => 
    array (
      'time' => 591130800,
      'type' => 1,
    ),
    18 => 
    array (
      'time' => 606855600,
      'type' => 2,
    ),
    19 => 
    array (
      'time' => 622580400,
      'type' => 1,
    ),
    20 => 
    array (
      'time' => 638305200,
      'type' => 2,
    ),
    21 => 
    array (
      'time' => 654634800,
      'type' => 1,
    ),
    22 => 
    array (
      'time' => 670359600,
      'type' => 0,
    ),
    23 => 
    array (
      'time' => 670363200,
      'type' => 3,
    ),
    24 => 
    array (
      'time' => 686088000,
      'type' => 0,
    ),
    25 => 
    array (
      'time' => 695764800,
      'type' => 1,
    ),
    26 => 
    array (
      'time' => 701798400,
      'type' => 2,
    ),
    27 => 
    array (
      'time' => 717519600,
      'type' => 1,
    ),
    28 => 
    array (
      'time' => 738090000,
      'type' => 0,
    ),
    29 => 
    array (
      'time' => 748987200,
      'type' => 0,
    ),
    30 => 
    array (
      'time' => 764712000,
      'type' => 3,
    ),
    31 => 
    array (
      'time' => 780436800,
      'type' => 0,
    ),
    32 => 
    array (
      'time' => 796161600,
      'type' => 3,
    ),
    33 => 
    array (
      'time' => 811886400,
      'type' => 0,
    ),
    34 => 
    array (
      'time' => 828216000,
      'type' => 3,
    ),
    35 => 
    array (
      'time' => 846360000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 21600,
    'name' => 'NOV%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 2,
      'date' => -1,
      'day_of_week' => 1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'end' => 
    array (
      'month' => 9,
      'date' => -1,
      'day_of_week' => 1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'startYear' => 1997,
  ),
  'name' => 'Asia/Novosibirsk',
);

?>