<?php

/**
 * Data file for Asia/Baghdad timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 10656,
      'dstOffset' => 0,
      'name' => 'BMT',
    ),
    1 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 0,
      'name' => 'AST',
    ),
    2 => 
    array (
      'rawOffset' => 10800,
      'dstOffset' => 3600,
      'name' => 'ADT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524532260,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1641005856,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 389048400,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 402264000,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 417906000,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 4.338E+8,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 449614800,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => 465422400,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 481154400,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => 496792800,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 512517600,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => 528242400,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => 543967200,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => 559692000,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => 575416800,
      'type' => 2,
    ),
    15 => 
    array (
      'time' => 591141600,
      'type' => 1,
    ),
    16 => 
    array (
      'time' => 606866400,
      'type' => 2,
    ),
    17 => 
    array (
      'time' => 622591200,
      'type' => 1,
    ),
    18 => 
    array (
      'time' => 638316000,
      'type' => 2,
    ),
    19 => 
    array (
      'time' => 654645600,
      'type' => 1,
    ),
    20 => 
    array (
      'time' => 670464000,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 10800,
    'name' => 'A%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 3,
      'date' => '1',
      'day_of_week' => 0,
      'time' => 1.08E+7,
      'type' => 1,
    ),
    'end' => 
    array (
      'month' => 9,
      'date' => '1',
      'day_of_week' => 0,
      'time' => 1.08E+7,
      'type' => 1,
    ),
    'startYear' => 1992,
  ),
  'name' => 'Asia/Baghdad',
);

?>