<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -7200,
      'dstOffset' => 0,
      'name' => 'GST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524512832,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GST',
    'offset' => -7200,
    'startYear' => 1891,
  ),
  'name' => 'Atlantic/South_Georgia',
)
?>