<?php

/**
 * Data file for Atlantic/South_Georgia timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/10/2008 14:19:43
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -7200,
      'dstOffset' => 0,
      'name' => 'GST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2524512832,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GST',
    'offset' => -7200,
    'startYear' => 1891,
  ),
  'name' => 'Atlantic/South_Georgia',
);

?>