<?php

/**
 * Data file for Australia/Adelaide timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
    1 => 
    array (
      'rawOffset' => 34200,
      'dstOffset' => 0,
      'name' => 'CST',
    ),
    2 => 
    array (
      'rawOffset' => 34200,
      'dstOffset' => 3600,
      'name' => 'CST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2364110060,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -2230189200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1672565340,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -1665390600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -883639800,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => -876126600,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -860398200,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => -844677000,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => -828343800,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => -813227400,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 31501800,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 57688200,
      'type' => 2,
    ),
    12 => 
    array (
      'time' => 67969800,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 89137800,
      'type' => 2,
    ),
    14 => 
    array (
      'time' => 100024200,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 120587400,
      'type' => 2,
    ),
    16 => 
    array (
      'time' => 131473800,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 152037000,
      'type' => 2,
    ),
    18 => 
    array (
      'time' => 152037000,
      'type' => 2,
    ),
    19 => 
    array (
      'time' => 162923400,
      'type' => 1,
    ),
    20 => 
    array (
      'time' => 183486600,
      'type' => 2,
    ),
    21 => 
    array (
      'time' => 183486600,
      'type' => 2,
    ),
    22 => 
    array (
      'time' => 194977800,
      'type' => 1,
    ),
    23 => 
    array (
      'time' => 215541000,
      'type' => 2,
    ),
    24 => 
    array (
      'time' => 215541000,
      'type' => 2,
    ),
    25 => 
    array (
      'time' => 226427400,
      'type' => 1,
    ),
    26 => 
    array (
      'time' => 246990600,
      'type' => 2,
    ),
    27 => 
    array (
      'time' => 246990600,
      'type' => 2,
    ),
    28 => 
    array (
      'time' => 257877000,
      'type' => 1,
    ),
    29 => 
    array (
      'time' => 278440200,
      'type' => 2,
    ),
    30 => 
    array (
      'time' => 278440200,
      'type' => 2,
    ),
    31 => 
    array (
      'time' => 289326600,
      'type' => 1,
    ),
    32 => 
    array (
      'time' => 309889800,
      'type' => 2,
    ),
    33 => 
    array (
      'time' => 309889800,
      'type' => 2,
    ),
    34 => 
    array (
      'time' => 320776200,
      'type' => 1,
    ),
    35 => 
    array (
      'time' => 341339400,
      'type' => 2,
    ),
    36 => 
    array (
      'time' => 341339400,
      'type' => 2,
    ),
    37 => 
    array (
      'time' => 352225800,
      'type' => 1,
    ),
    38 => 
    array (
      'time' => 372789000,
      'type' => 2,
    ),
    39 => 
    array (
      'time' => 372789000,
      'type' => 2,
    ),
    40 => 
    array (
      'time' => 384280200,
      'type' => 1,
    ),
    41 => 
    array (
      'time' => 404843400,
      'type' => 2,
    ),
    42 => 
    array (
      'time' => 404843400,
      'type' => 2,
    ),
    43 => 
    array (
      'time' => 415729800,
      'type' => 1,
    ),
    44 => 
    array (
      'time' => 436293000,
      'type' => 2,
    ),
    45 => 
    array (
      'time' => 436293000,
      'type' => 2,
    ),
    46 => 
    array (
      'time' => 447179400,
      'type' => 1,
    ),
    47 => 
    array (
      'time' => 467742600,
      'type' => 2,
    ),
    48 => 
    array (
      'time' => 467742600,
      'type' => 2,
    ),
    49 => 
    array (
      'time' => 478629000,
      'type' => 1,
    ),
    50 => 
    array (
      'time' => 499192200,
      'type' => 2,
    ),
    51 => 
    array (
      'time' => 499192200,
      'type' => 2,
    ),
    52 => 
    array (
      'time' => 511288200,
      'type' => 1,
    ),
    53 => 
    array (
      'time' => 530037000,
      'type' => 2,
    ),
    54 => 
    array (
      'time' => 530641800,
      'type' => 2,
    ),
    55 => 
    array (
      'time' => 542737800,
      'type' => 1,
    ),
    56 => 
    array (
      'time' => 574792200,
      'type' => 1,
    ),
    57 => 
    array (
      'time' => 594145800,
      'type' => 2,
    ),
    58 => 
    array (
      'time' => 606241800,
      'type' => 1,
    ),
    59 => 
    array (
      'time' => 625595400,
      'type' => 2,
    ),
    60 => 
    array (
      'time' => 637691400,
      'type' => 1,
    ),
    61 => 
    array (
      'time' => 657045000,
      'type' => 2,
    ),
    62 => 
    array (
      'time' => 667931400,
      'type' => 1,
    ),
    63 => 
    array (
      'time' => 701195400,
      'type' => 1,
    ),
    64 => 
    array (
      'time' => 731435400,
      'type' => 1,
    ),
    65 => 
    array (
      'time' => 764094600,
      'type' => 1,
    ),
    66 => 
    array (
      'time' => 796149000,
      'type' => 1,
    ),
    67 => 
    array (
      'time' => 828203400,
      'type' => 1,
    ),
    68 => 
    array (
      'time' => 846347400,
      'type' => 2,
    ),
    69 => 
    array (
      'time' => 859653000,
      'type' => 1,
    ),
    70 => 
    array (
      'time' => 877797000,
      'type' => 2,
    ),
    71 => 
    array (
      'time' => 891102600,
      'type' => 1,
    ),
    72 => 
    array (
      'time' => 909246600,
      'type' => 2,
    ),
    73 => 
    array (
      'time' => 922552200,
      'type' => 1,
    ),
    74 => 
    array (
      'time' => 941301000,
      'type' => 2,
    ),
    75 => 
    array (
      'time' => 954001800,
      'type' => 1,
    ),
    76 => 
    array (
      'time' => 972750600,
      'type' => 2,
    ),
    77 => 
    array (
      'time' => 985451400,
      'type' => 1,
    ),
    78 => 
    array (
      'time' => 1004200200,
      'type' => 2,
    ),
    79 => 
    array (
      'time' => 1017505800,
      'type' => 1,
    ),
    80 => 
    array (
      'time' => 1035649800,
      'type' => 2,
    ),
    81 => 
    array (
      'time' => 1048955400,
      'type' => 1,
    ),
    82 => 
    array (
      'time' => 1067099400,
      'type' => 2,
    ),
    83 => 
    array (
      'time' => 1080405000,
      'type' => 1,
    ),
    84 => 
    array (
      'time' => 1099153800,
      'type' => 2,
    ),
    85 => 
    array (
      'time' => 1111854600,
      'type' => 1,
    ),
    86 => 
    array (
      'time' => 1130603400,
      'type' => 2,
    ),
    87 => 
    array (
      'time' => 1143909000,
      'type' => 1,
    ),
    88 => 
    array (
      'time' => 1162053000,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 34200,
    'name' => 'CST',
    'save' => 3600,
    'start' => 
    array (
      'month' => 9,
      'date' => -1,
      'day_of_week' => 1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'end' => 
    array (
      'month' => 2,
      'date' => -1,
      'day_of_week' => 1,
      'time' => 7.2E+6,
      'type' => 1,
    ),
    'startYear' => 2007,
  ),
  'name' => 'Australia/Adelaide',
);

?>