<?php

/**
 * Data file for Australia/Brisbane timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/03/2007 17:31:56
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 36000,
      'dstOffset' => 0,
      'name' => 'EST',
    ),
    1 => 
    array (
      'rawOffset' => 36000,
      'dstOffset' => 3600,
      'name' => 'EST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2366791928,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1672567140,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1665392400,
      'type' => 0,
    ),
    3 => 
    array (
      'time' => -883641600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -876128400,
      'type' => 0,
    ),
    5 => 
    array (
      'time' => -8.604E+8,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -844678800,
      'type' => 0,
    ),
    7 => 
    array (
      'time' => -828345600,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => -813229200,
      'type' => 0,
    ),
    9 => 
    array (
      'time' => 3.15E+7,
      'type' => 0,
    ),
    10 => 
    array (
      'time' => 57686400,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 67968000,
      'type' => 0,
    ),
    12 => 
    array (
      'time' => 625593600,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 636480000,
      'type' => 0,
    ),
    14 => 
    array (
      'time' => 657043200,
      'type' => 1,
    ),
    15 => 
    array (
      'time' => 667929600,
      'type' => 0,
    ),
    16 => 
    array (
      'time' => 688492800,
      'type' => 1,
    ),
    17 => 
    array (
      'time' => 699379200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => 36000,
    'startYear' => 1993,
  ),
  'name' => 'Australia/Brisbane',
);

?>