<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 0,
      'name' => 'WST',
    ),
    1 => 
    array (
      'rawOffset' => 28800,
      'dstOffset' => 3600,
      'name' => 'WST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2337925404,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1672559940,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -1665385200,
      'type' => 0,
    ),
    3 => 
    array (
      'time' => -883634400,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => -876121200,
      'type' => 0,
    ),
    5 => 
    array (
      'time' => -860392800,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => -844671600,
      'type' => 0,
    ),
    7 => 
    array (
      'time' => -836467200,
      'type' => 0,
    ),
    8 => 
    array (
      'time' => 149788800,
      'type' => 1,
    ),
    9 => 
    array (
      'time' => 162831600,
      'type' => 0,
    ),
    10 => 
    array (
      'time' => 433785600,
      'type' => 1,
    ),
    11 => 
    array (
      'time' => 446914800,
      'type' => 0,
    ),
    12 => 
    array (
      'time' => 690314400,
      'type' => 1,
    ),
    13 => 
    array (
      'time' => 699375600,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WST',
    'offset' => 28800,
    'startYear' => 1993,
  ),
  'name' => 'Australia/Perth',
)
?>