<?php

/**
 * Data file for Etc/GMT-4 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/26/2009 23:55:29
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT-4',
    'offset' => 14400,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT-4',
);

?>