<?php

/**
 * Data file for Etc/GMT+7 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/17/2009 13:26:25
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT+7',
    'offset' => -25200,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT+7',
);

?>