<?php

/**
 * Data file for Etc/GMT-5 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/13/2009 16:13:10
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT-5',
    'offset' => 18000,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT-5',
);

?>