<?php

/**
 * Data file for Etc/GMT+11 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/19/2009 20:43:28
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT+11',
    'offset' => -39600,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT+11',
);

?>