<?php

/**
 * Data file for Etc/GMT-1 timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/10/2008 14:19:43
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GMT-1',
    'offset' => 3600,
    'startYear' => -2147483647,
  ),
  'name' => 'Etc/GMT-1',
);

?>