<?php

/**
 * Data file for HST timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/05/2009 16:44:34
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'HST',
    'offset' => -36000,
    'startYear' => -2147483647,
  ),
  'name' => 'HST',
);

?>