<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 18000,
      'dstOffset' => 0,
      'name' => 'TFT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -631152000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'TFT',
    'offset' => 18000,
    'startYear' => 1951,
  ),
  'name' => 'Indian/Kerguelen',
)
?>