<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 25200,
      'dstOffset' => 0,
      'name' => 'CXT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2364102172,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CXT',
    'offset' => 25200,
    'startYear' => 1896,
  ),
  'name' => 'Indian/Christmas',
)
?>