<?php

/**
 * Data file for Indian/Cocos timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/25/2009 14:53:37
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 23400,
      'dstOffset' => 0,
      'name' => 'CCT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2209012060,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CCT',
    'offset' => 23400,
    'startYear' => 1900,
  ),
  'name' => 'Indian/Cocos',
);

?>