<?php

/**
 * Data file for Indian/Chagos timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/06/2009 11:49:09
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 18000,
      'dstOffset' => 0,
      'name' => 'IOT',
    ),
    1 => 
    array (
      'rawOffset' => 21600,
      'dstOffset' => 0,
      'name' => 'IOT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1988167780,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 820436400,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'IOT',
    'offset' => 21600,
    'startYear' => 1996,
  ),
  'name' => 'Indian/Chagos',
);

?>