<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'MUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1988164200,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'MUT',
    'offset' => 14400,
    'startYear' => 1907,
  ),
  'name' => 'Indian/Mauritius',
)
?>