<?php

/**
 * Data file for Indian/Reunion timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/19/2009 20:43:28
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 14400,
      'dstOffset' => 0,
      'name' => 'RET',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1848886912,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'RET',
    'offset' => 14400,
    'startYear' => 1912,
  ),
  'name' => 'Indian/Reunion',
);

?>