<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 23400,
      'dstOffset' => 0,
      'name' => 'CCT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2209012060,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'CCT',
    'offset' => 23400,
    'startYear' => 1900,
  ),
  'name' => 'Indian/Cocos',
)
?>