<?php

/**
 * Data file for Indian/Kerguelen timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/05/2009 16:44:34
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 18000,
      'dstOffset' => 0,
      'name' => 'TFT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -631152000,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'TFT',
    'offset' => 18000,
    'startYear' => 1951,
  ),
  'name' => 'Indian/Kerguelen',
);

?>