<?php

/**
 * Data file for Pacific/Tahiti timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 03/16/2009 17:45:26
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -36000,
      'dstOffset' => 0,
      'name' => 'TAHT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1806674504,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'TAHT',
    'offset' => -36000,
    'startYear' => 1913,
  ),
  'name' => 'Pacific/Tahiti',
);

?>