<?php

/**
 * Data file for Pacific/Wallis timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/06/2009 11:49:09
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'WFT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177496920,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WFT',
    'offset' => 43200,
    'startYear' => 1901,
  ),
  'name' => 'Pacific/Wallis',
);

?>