<?php

/**
 * Data file for Pacific/Kiritimati timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 09/11/2009 10:31:33
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -38400,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
    1 => 
    array (
      'rawOffset' => -36000,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
    2 => 
    array (
      'rawOffset' => 50400,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177415040,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 307622400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 788954400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'LINT',
    'offset' => 50400,
    'startYear' => 1996,
  ),
  'name' => 'Pacific/Kiritimati',
);

?>