<?php

/**
 * Data file for Pacific/Fiji timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/15/2009 15:47:05
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'FJT',
    ),
    1 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 3600,
      'name' => 'FJST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1709985220,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 909842400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 920124000,
      'type' => 0,
    ),
    3 => 
    array (
      'time' => 941900400,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 951573600,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'none',
    'offset' => 43200,
    'startYear' => 2001,
  ),
  'name' => 'Pacific/Fiji',
);

?>