<?php

/**
 * Data file for Pacific/Kosrae timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 08/10/2008 14:19:43
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 39600,
      'dstOffset' => 0,
      'name' => 'KOST',
    ),
    1 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'KOST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177491916,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -7988400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 915105600,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'KOST',
    'offset' => 39600,
    'startYear' => 1999,
  ),
  'name' => 'Pacific/Kosrae',
);

?>