<?php

/**
 * Data file for Pacific/Gambier timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 06/15/2009 15:47:05
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -32400,
      'dstOffset' => 0,
      'name' => 'GAMT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1806678012,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GAMT',
    'offset' => -32400,
    'startYear' => 1913,
  ),
  'name' => 'Pacific/Gambier',
);

?>