<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -40800,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
    1 => 
    array (
      'rawOffset' => -41400,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
    2 => 
    array (
      'rawOffset' => -39600,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177412020,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -599575200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 276089400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'NUT',
    'offset' => -39600,
    'startYear' => 1979,
  ),
  'name' => 'Pacific/Niue',
)
?>