<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -38400,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
    1 => 
    array (
      'rawOffset' => -36000,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
    2 => 
    array (
      'rawOffset' => 50400,
      'dstOffset' => 0,
      'name' => 'LINT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177415040,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 307622400,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 788954400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'LINT',
    'offset' => 50400,
    'startYear' => 1996,
  ),
  'name' => 'Pacific/Kiritimati',
)
?>