<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
  ),
  'rules' => 
  array (
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'HST',
    'offset' => -36000,
    'startYear' => -2147483647,
  ),
  'name' => 'Pacific/Johnston',
)
?>