<?php

/**
 * Data file for Pacific/Funafuti timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  (c) Authors
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'TVT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177495812,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'TVT',
    'offset' => 43200,
    'startYear' => 1901,
  ),
  'name' => 'Pacific/Funafuti',
);

?>