<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 32400,
      'dstOffset' => 0,
      'name' => 'PWT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177485076,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'PWT',
    'offset' => 32400,
    'startYear' => 1901,
  ),
  'name' => 'Pacific/Palau',
)
?>