<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 39600,
      'dstOffset' => 0,
      'name' => 'SBT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1806748788,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SBT',
    'offset' => 39600,
    'startYear' => 1913,
  ),
  'name' => 'Pacific/Guadalcanal',
)
?>