<?php

/**
 * Data file for Pacific/Pago_Pago timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/19/2009 20:43:28
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -40968,
      'dstOffset' => 0,
      'name' => 'LMT',
    ),
    1 => 
    array (
      'rawOffset' => -41400,
      'dstOffset' => 0,
      'name' => 'SAMT',
    ),
    2 => 
    array (
      'rawOffset' => -39600,
      'dstOffset' => 0,
      'name' => 'NST',
    ),
    3 => 
    array (
      'rawOffset' => -39600,
      'dstOffset' => 0,
      'name' => 'BST',
    ),
    4 => 
    array (
      'rawOffset' => -39600,
      'dstOffset' => 0,
      'name' => 'SST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2855738232,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -1861879032,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => -631110600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => -86878800,
      'type' => 3,
    ),
    4 => 
    array (
      'time' => 439038000,
      'type' => 4,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SST',
    'offset' => -39600,
    'startYear' => 1984,
  ),
  'name' => 'Pacific/Pago_Pago',
);

?>