<?php

/**
 * Data file for Pacific/Marquesas timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 01/29/2009 09:07:19
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -34200,
      'dstOffset' => 0,
      'name' => 'MART',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1806676920,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'MART',
    'offset' => -34200,
    'startYear' => 1913,
  ),
  'name' => 'Pacific/Marquesas',
);

?>