<?php

/**
 * Data file for Pacific/Guadalcanal timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/29/2009 04:12:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 39600,
      'dstOffset' => 0,
      'name' => 'SBT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -1806748788,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'SBT',
    'offset' => 39600,
    'startYear' => 1913,
  ),
  'name' => 'Pacific/Guadalcanal',
);

?>