<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -30600,
      'dstOffset' => 0,
      'name' => 'PNT',
    ),
    1 => 
    array (
      'rawOffset' => -28800,
      'dstOffset' => 0,
      'name' => 'PST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177421580,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 893665800,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'PST',
    'offset' => -28800,
    'startYear' => 1999,
  ),
  'name' => 'Pacific/Pitcairn',
)
?>