<?php 
	// auto-generated by the phing olson task at 11/03/2006 07:32:19
	return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'GILT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177494324,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'GILT',
    'offset' => 43200,
    'startYear' => 1901,
  ),
  'name' => 'Pacific/Tarawa',
)
?>