<?php

/**
 * Data file for Pacific/Niue timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/26/2009 23:55:29
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -40800,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
    1 => 
    array (
      'rawOffset' => -41400,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
    2 => 
    array (
      'rawOffset' => -39600,
      'dstOffset' => 0,
      'name' => 'NUT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177412020,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => -599575200,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 276089400,
      'type' => 2,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'NUT',
    'offset' => -39600,
    'startYear' => 1979,
  ),
  'name' => 'Pacific/Niue',
);

?>