<?php

/**
 * Data file for Pacific/Chatham timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 11/05/2006 20:16:23
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  (c) Authors
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 45900,
      'dstOffset' => 0,
      'name' => 'CHAT',
    ),
    1 => 
    array (
      'rawOffset' => 45900,
      'dstOffset' => 3600,
      'name' => 'CHADT',
    ),
    2 => 
    array (
      'rawOffset' => 45900,
      'dstOffset' => 0,
      'name' => 'CHAST',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -410271228,
      'type' => 0,
    ),
    1 => 
    array (
      'time' => 152632800,
      'type' => 1,
    ),
    2 => 
    array (
      'time' => 162309600,
      'type' => 2,
    ),
    3 => 
    array (
      'time' => 183477600,
      'type' => 1,
    ),
    4 => 
    array (
      'time' => 194968800,
      'type' => 2,
    ),
    5 => 
    array (
      'time' => 215532000,
      'type' => 1,
    ),
    6 => 
    array (
      'time' => 226418400,
      'type' => 2,
    ),
    7 => 
    array (
      'time' => 246981600,
      'type' => 1,
    ),
    8 => 
    array (
      'time' => 257868000,
      'type' => 2,
    ),
    9 => 
    array (
      'time' => 278431200,
      'type' => 1,
    ),
    10 => 
    array (
      'time' => 289317600,
      'type' => 2,
    ),
    11 => 
    array (
      'time' => 309880800,
      'type' => 1,
    ),
    12 => 
    array (
      'time' => 320767200,
      'type' => 2,
    ),
    13 => 
    array (
      'time' => 341330400,
      'type' => 1,
    ),
    14 => 
    array (
      'time' => 352216800,
      'type' => 2,
    ),
    15 => 
    array (
      'time' => 372780000,
      'type' => 1,
    ),
    16 => 
    array (
      'time' => 384271200,
      'type' => 2,
    ),
    17 => 
    array (
      'time' => 404834400,
      'type' => 1,
    ),
    18 => 
    array (
      'time' => 415720800,
      'type' => 2,
    ),
    19 => 
    array (
      'time' => 436284000,
      'type' => 1,
    ),
    20 => 
    array (
      'time' => 447170400,
      'type' => 2,
    ),
    21 => 
    array (
      'time' => 467733600,
      'type' => 1,
    ),
    22 => 
    array (
      'time' => 478620000,
      'type' => 2,
    ),
    23 => 
    array (
      'time' => 499183200,
      'type' => 1,
    ),
    24 => 
    array (
      'time' => 510069600,
      'type' => 2,
    ),
    25 => 
    array (
      'time' => 530632800,
      'type' => 1,
    ),
    26 => 
    array (
      'time' => 541519200,
      'type' => 2,
    ),
    27 => 
    array (
      'time' => 562082400,
      'type' => 1,
    ),
    28 => 
    array (
      'time' => 573573600,
      'type' => 2,
    ),
    29 => 
    array (
      'time' => 594136800,
      'type' => 1,
    ),
    30 => 
    array (
      'time' => 605023200,
      'type' => 2,
    ),
    31 => 
    array (
      'time' => 623772000,
      'type' => 1,
    ),
    32 => 
    array (
      'time' => 655221600,
      'type' => 1,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'dynamic',
    'offset' => 45900,
    'name' => 'CHA%sT',
    'save' => 3600,
    'start' => 
    array (
      'month' => 9,
      'date' => '1',
      'day_of_week' => -1,
      'time' => 9.9E+6,
      'type' => 1,
    ),
    'end' => 
    array (
      'month' => 2,
      'date' => '15',
      'day_of_week' => -1,
      'time' => 9.9E+6,
      'type' => 1,
    ),
    'startYear' => 1991,
  ),
  'name' => 'Pacific/Chatham',
);

?>