<?php

/**
 * Data file for Pacific/Wake timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 04/29/2009 04:12:07
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => 43200,
      'dstOffset' => 0,
      'name' => 'WAKT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177492788,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'WAKT',
    'offset' => 43200,
    'startYear' => 1901,
  ),
  'name' => 'Pacific/Wake',
);

?>