<?php

/**
 * Data file for Pacific/Fakaofo timezone, compiled from the olson data.
 *
 * Auto-generated by the phing olson task on 10/26/2009 23:55:29
 *
 * @package    agavi
 * @subpackage translation
 *
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */

return array (
  'types' => 
  array (
    0 => 
    array (
      'rawOffset' => -36000,
      'dstOffset' => 0,
      'name' => 'TKT',
    ),
  ),
  'rules' => 
  array (
    0 => 
    array (
      'time' => -2177411704,
      'type' => 0,
    ),
  ),
  'finalRule' => 
  array (
    'type' => 'static',
    'name' => 'TKT',
    'offset' => -36000,
    'startYear' => 1902,
  ),
  'name' => 'Pacific/Fakaofo',
);

?>