<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2003-2006 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+

/**
 * AgaviCompileConfigHandler gathers multiple files and puts them into a single
 * file. Upon creation of the new file, all comments and blank lines are removed.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @author     Dominik del Bondio <ddb@bitxtender.com>
 * @copyright  (c) Authors
 * @since      0.9.0
 *
 * @version    $Id$
 */
class AgaviCompileConfigHandler extends AgaviConfigHandler
{

	/**
	 * Execute this configuration handler.
	 *
	 * @param      string An absolute filesystem path to a configuration file.
	 *
	 * @return     string Data to be written to a cache file.
	 *
	 * @throws     <b>AgaviUnreadableException</b> If a requested configuration file
	 *                                             does not exist or is not readable.
	 * @throws     <b>AgaviParseException</b> If a requested configuration file is
	 *                                        improperly formatted.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @author     Dominik del Bondio <ddb@bitxtender.com>
	 * @since      0.9.0
	 */
	public function execute($config, $context = null)
	{
		// parse the config file
		$configurations = $this->orderConfigurations(AgaviConfigCache::parseConfig($config, false, $this->getValidationFile())->configurations, AgaviConfig::get('core.environment'));

		$data = array();

		// let's do our fancy work
		foreach($configurations as $configuration) {
			foreach($configuration->compiles as $compileFile) {
				$file = trim($compileFile->getValue());

				$file = $this->replaceConstants($file);
				$file = $this->replacePath($file);
				$file = realpath($file);

				if(!is_readable($file)) {
					// file doesn't exist
					$error = 'Configuration file "%s" specifies nonexistent ' . 'or unreadable file "%s"';
					$error = sprintf($error, $config, $file);
					throw new AgaviParseException($error);
				}

				if(AgaviConfig::get('core.debug', false)) {
					// debug mode, just require() the files, makes for nicer stack traces
					$contents = 'require(' . var_export($file, true) . ');';
				} else {
					// no debug mode, so make things fast
					$contents = trim(file_get_contents($file));
					
					if(substr($contents, 0, 5) == '<?php') {
						$contents = substr($contents, 5);
					} elseif(substr($contents, 0, 2) == '<?') {
						$contents = substr($contents, 2);
					}
					if(substr($contents, -2, 2) == '?>') {
						$contents = substr($contents, 0, -2);
					}
				}

				// append file data
				$data[$file] = $contents;
			}
		}
		
		$data = implode("\n", $data);

		if(!AgaviConfig::get('core.debug', false)) {
			$data = $this->formatFile($data);
		}

		// compile data
		$retval = "<?php\n" .
				  "// auto-generated by CompileConfigHandler\n" .
				  "// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), $data);

		return $retval;
	}

	/**
	 * Given some data, remove unnecessary formatting and return the new data
	 *
	 * @param      string Data to format for a compiled file, probably PHP code
	 *
	 * @return     string Data with unnecessary content removed
	 *
	 * @author     Blake Matheny (bmatheny@mobocracy.net)
	 * @author     David Zuelke (dz@bitxtender.com)
	 * @since      0.11.0
	 */
	protected function formatFile ($data)
	{
		// replace windows and mac format with unix format
		$data = str_replace("\r\n", "\n", $data);
		$data = str_replace("\r", "\n", $data);

		// remove comments and tags with tokenizer
		
		// I disabled this, it seems broken somehow. doesn't remove all <?php tags. - david
		
		if(function_exists('token_get_all_DISABLED_IT_BECAUSE_TOKENIZER_SEEMS_BROKEN')) {
			$tokens = token_get_all($data);
			$tokenized = null;
			// has something been written to tokenized? If so, we can optionally append whitespace.
			$appended = false;

			foreach($tokens as $token) {

				if(is_string($token)) {
					$tokenized .= $token;
					$appended = true;
				} else {
					@list($id,$text) = $token;
					switch($id) {
						case T_COMMENT:
						case T_DOC_COMMENT:
						case T_OPEN_TAG:
							$appended = false;
							break;
						case T_CLOSE_TAG:
							$appended = false;
							break;

						case T_WHITESPACE:
							// something was appended, optionally add a newline
							if($appended) {
								$replace = null;
								if(strstr($text, "\n") !== false) {
									$replace = "\n";
								}
								if($replace) {
									$text = preg_replace("/\s+/m", $replace, $text);
								}
								$tokenized .= $text;
							}
							$appended = false;
							break;

						case T_INLINE_HTML:
							// If empty T_INLINE_HTML move on
							if(!preg_match('/[^\s]+/m', $text)) {
								$appended = false;
								break;
							}

						default:
							$tokenized .= $text;
							$appended = true;
							break;
					}
				}
			}
			$data = $tokenized;
		} else {
			// no tokenizer support, let's do some basic cleanup
			$data = trim($data);
			$data = preg_replace('/\s\?>\s<\?(php)?\s/u', '', $data);
		}

		return $data;
	}

}

?>