<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2003-2006 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+

/**
 * AgaviAutoloadConfigHandler allows you to specify a list of classes that will
 * automatically be included for you upon first use.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @author     Dominik del Bondio <ddb@bitxtender.com>
 * @copyright  (c) Authors
 * @since      0.9.0
 *
 * @version    $Id$
 */
class AgaviAutoloadConfigHandler extends AgaviConfigHandler
{
	/**
	 * Execute this configuration handler.
	 *
	 * @param      string An absolute filesystem path to a configuration file.
	 * @param      string Name of the executing context (if any).
	 *
	 * @return     string Data to be written to a cache file.
	 *
	 * @throws     <b>AgaviUnreadableException</b> If a requested configuration file
	 *                                             does not exist or is not readable.
	 * @throws     <b>AgaviParseException</b> If a requested configuration file is
	 *                                        improperly formatted.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @author     Dominik del Bondio <ddb@bitxtender.com>
	 * @since      0.9.0
	 */
	public function execute($config, $context = null)
	{

		$data = $this->parseFile($config);
		if(($sysConfDir = AgaviConfig::get('core.system_config_dir'))) {
			$data = array_merge($data, $this->parseFile($sysConfDir . '/autoload.xml'));
		}

		$code = 'Agavi::setAutoloads(' . var_export($data, true) . ');';

		// compile data
		$retval = "<?php\n" .
				  "// auth-generated by AutoloadConfigHandler\n" .
				  "// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), $code);

		return $retval;

	}


	protected function parseFile($config)
	{
		// parse the config file
		$conf = AgaviConfigCache::parseConfig($config, false);

		$data = array();
		$environment = AgaviConfig::get('core.environment');
		foreach($conf->configurations as $config)
		{
			$env = $environment;
			if($config->hasAttribute('environment'))
				$env = $config->getAttribute('environment');

			// let's do our fancy work
			foreach($config->autoloads as $entry) {

				$file = $this->replaceConstants($entry->getValue());
				$class = $entry->getAttribute('name');

				if(!($fp = @fopen($file, 'r', true))) {

					// the class path doesn't exist
					$error = 'Configuration file "%s" specifies class "%s" with ' .
							 'nonexistent or unreadable file "%s"';
					$error = sprintf($error, $config, $class, $file);

					throw new AgaviParseException($error);
				}
				fclose($fp);

				if($env == $environment)
					$data[$class] = $file;
			}
		}
		return $data;
	}

}

?>