<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2003-2006 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+

/**
 * AgaviDefineConfigHandler allows you to turn ini categories and key/value
 * pairs into defined PHP values.
 *
 * <b>Optional initialization parameters:</b>
 *
 * # <b>prefix</b> - The text prepended to all defined constant names.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @copyright  (c) Authors
 * @since      0.9.0
 *
 * @version    $Id$
 */
class AgaviDefineConfigHandler extends AgaviConfigHandler
{

	/**
	 * Execute this configuration handler.
	 *
	 * @param      string An absolute filesystem path to a configuration file.
	 *
	 * @return     string Data to be written to a cache file.
	 *
	 * @throws     <b>AgaviUnreadableException</b> If a requested configuration file
	 *                                             does not exist or is not readable.
	 * @throws     <b>AgaviParseException</b> If a requested configuration file is
	 *                                        improperly formatted.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @since      0.9.0
	 */
	public function execute($config, $context = null)
	{

		$conf = AgaviConfigCache::parseConfig($config, false);

		// init our data array
		$data = array();
		$environment = AgaviConfig::get('core.environment');

		foreach($conf->configurations as $config)
		{
			$env = $environment;
			if($config->hasAttribute('environment'))
				$env = $config->getAttribute('environment');

			if($env != $environment)
				continue;

			// let's do our fancy work
			if($config->hasChildren('system_actions')) {
				foreach($config->system_actions->getChildren() as $action) {
					$name = $action->getAttribute('name');
					$data[sprintf('actions.%s_module', $name)] = $action->module->getValue();
					$data[sprintf('actions.%s_action', $name)] = $action->action->getValue();
				}
			}

			foreach($config->settings as $setting)
			{
				$data[$setting->getAttribute('name')] = $this->literalize($this->replaceConstants($setting->getValue()));
			}

		}

		$code = 'AgaviConfig::import(' . var_export($data, true) . ');';

		// compile data
		$retval = "<?php\n" .
				  "// auto-generated by DefineConfigHandler\n" .
				  "// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), $code);

		return $retval;

	}

}

?>