<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2003-2006 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+

/**
 * AgaviFactoryConfigHandler allows you to specify which factory implementation 
 * the system will use.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @author     Mike Vincent <mike@agavi.org>
 * @copyright  (c) Authors
 * @since      0.9.0
 *
 * @version    $Id$
 */
class AgaviFactoryConfigHandler extends AgaviConfigHandler
{

	/**
	 * Execute this configuration handler.
	 *
	 * @param      string An absolute filesystem path to a configuration file.
	 *
	 * @return     string Data to be written to a cache file.
	 *
	 * @throws     <b>AgaviUnreadableException</b> If a requested configuration file
	 *                                             does not exist or is not readable.
	 * @throws     <b>AgaviParseException</b> If a requested configuration file is
	 *                                        improperly formatted.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @since      0.9.0
	 */
	public function execute($config, $context = null)
	{
		if($context == null) {
			$context = '';
		}

		// parse the config file
		$conf = AgaviConfigCache::parseConfig($config);

		$data = array();
		foreach($conf->configurations as $cfg)
		{
			$code = array();

			$ctx = $context;
			if($cfg->hasAttribute('context'))
				$ctx = $cfg->getAttribute('context');

			$requiredItems = array('action_stack', 'controller', 'database_manager', 'logger_manager', 'request', 'storage', 'user', 'validator_manager');
			$definedItems = array_keys($cfg->getChildren());
			if(count($missingItems = array_diff($requiredItems, $definedItems)) > 0) {
					$error = 'Configuration file "%s" is missing key(s) %s';
					$error = sprintf($error, $config, implode(' ', $missingItems));
					throw new AgaviParseException($error);
			}
			

			// The order of this initialisiation code is fixed, to not change

			if(AgaviConfig::get('core.use_database', false)) {
				$code[] = '$this->databaseManager = new ' . $cfg->database_manager->class->getValue() . '();';
				$code[] = '$this->databaseManager->initialize($this);';
			}

			// Actionstack
			$code[] = '$this->actionStack = new ' . $cfg->action_stack->class->getValue() . '();';

			// Request
			$code[] = '$this->request = AgaviRequest::newInstance("' . $cfg->request->class->getValue() . '");';

			// Request
			$code[] = '$this->routing = new ' . $cfg->routing->class->getValue() . '();';

			// Storage
			$code[] = '$this->storage = AgaviStorage::newInstance("' . $cfg->storage->class->getValue() . '");';
			$code[] = '$this->storage->initialize($this, ' . $this->getSettings($cfg->storage) . ');';
			$code[] = '$this->storage->startup();';

			// ValidatorManager
			$code[] = '$this->validatorManager = new ' . $cfg->validator_manager->class->getValue() . '();';
			$code[] = '$this->validatorManager->initialize($this);';

			// User
			if(AgaviConfig::get('core.use_security', true)) {
				$code[] = '$this->user = AgaviUser::newInstance("' . $cfg->user->class->getValue() . '");';
				$code[] = '$this->user->initialize($this, ' . $this->getSettings($cfg->user) . ');';
			}

			// LoggerManager
			if(AgaviConfig::get('core.use_logging', false)) {
				$code[] = '$this->loggerManager = new ' . $cfg->logger_manager->class->getValue() . '();';
				$code[] = '$this->loggerManager->initialize($this);';

			}

			// Controller 
			$code[] = '$this->controller = AgaviController::newInstance("' . $cfg->controller->class->getValue() . '");';
			$code[] = '$this->controller->initialize($this, ' . $this->getSettings($cfg->controller) . ');';
		
			$code[] = '$this->request->initialize($this, ' . $this->getSettings($cfg->request) . ');';
		}


		// compile data
		$retval = "<?php\n" .
		"// auto-generated by FactoryConfigHandler\n" .
		"// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), implode("\n", $code));

		return $retval;

	}

	protected function getSettings($itemNode)
	{
		$data = array();
		if($itemNode->hasChildren('settings')) {
			foreach($itemNode->settings as $node) {
				$data[$node->getAttribute('name')] = $node->getValue();
			}
		}
		return var_export($data, true);
	}

}

?>