<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2003-2006 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+

/**
 * AgaviFilterConfigHandler allows you to register filters with the system.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @copyright  (c) Authors
 * @since      0.9.0
 *
 * @version    $Id$
 */
class AgaviFilterConfigHandler extends AgaviIniConfigHandler
{
	protected function getItemParameters($itemNode, $oldValues = array())
	{
		$data = array();
		if($itemNode->hasChildren('parameters')) {
			foreach($itemNode->parameters as $node) {
				$data[$node->getAttribute('name')] = $this->literalize($node->getValue());
			}
		}
		$data = array_merge($oldValues, $data);
		return $data;
	}

	/**
	 * Execute this configuration handler.
	 *
	 * @param      string An absolute filesystem path to a configuration file.
	 *
	 * @return     string Data to be written to a cache file.
	 *
	 * @throws     <b>AgaviUnreadableException</b> If a requested configuration file
	 *                                             does not exist or is not readable.
	 * @throws     <b>AgaviParseException</b> If a requested configuration file is
	 *                                        improperly formatted.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @since      0.9.0
	 */
	public function execute($config, $context = null)
	{
		// parse the config file
		$conf = AgaviConfigCache::parseConfig($config, false);

		$filters = array(
			'filters' => array(),
			'execution_filter' => '',
			'security_filter' => array('class' => '', 'params' => array()),
			);
		$environment = AgaviConfig::get('core.environment');
		foreach($conf->configurations as $cfg) {
			$env = $cfg->hasAttribute('environment') ? $cfg->getAttribute('environment') : $environment;
			$ctx = $cfg->hasAttribute('context') ? $cfg->getAttribute('context') : $context;

			if($env != $environment || $ctx != $context)
				continue;

			if($cfg->hasChildren('execution_filter')) {
				$filters['execution_filter'] = $cfg->execution_filter->class->getValue();
			}

			if($cfg->hasChildren('security_filter')) {
				if($cfg->execution_filter->hasChildren('class'))
					$filters['security_filter']['class'] = $cfg->execution_filter->class->getValue();
				$filters['security_filter']['params'] = $this->getItemParameters($cfg->execution_filter, $filters['security_filter']['params']);
			}

			if($cfg->hasChildren('filters')) {
				foreach($cfg->filters as $filter) {
					$name = $filter->getAttribute('name');
					if(!isset($filters['filters'][$name]))
						$filters['filters'][$name] = array('params' => array());

					if($filter->hasChildren('class'))
						$filters['filters'][$name]['class'] = $filter->class->getValue();
					$filters['filters'][$name]['params'] = $this->getItemParameters($filter, $filters['filters'][$name]['params']);
				}
			}
		}

		$data = array();
		$data[] = '$this->setExecutionFilterClassName("' . $filters['execution_filter'] . '");';

		foreach($filters['filters'] as $filter) {
			$data[] = '$filter = new ' . $filter['class'] . '();';
			$data[] = '$filter->initialize($this->context, ' . var_export($filter['params'], true) . ');';
			$data[] = '$filters[] = $filter;';
		}

		// compile data
		$retval = "<?php\n" .
				"// auto-generated by FilterConfigHandler\n" .
				"// date: %s\n%s\n%s\n%s\n?>";

		$retval = sprintf($retval, date('m/d/Y H:i:s'),
						  '$filters = array();',
						  implode("\n", $data),
						  '$list[$moduleName] = $filters;');

		return $retval;

	}

}

?>