<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61679',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61692',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/index.php',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61693',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/index.php?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61696',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/index.php/fubar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61698',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'Agavi=ljjevpuvgtg5rf9h0mq2i6gpu5',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '56982',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'test=foo%20bar+baz',
			'REQUEST_URI' => '/~dzuelke/rw/index.php/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fo o&ba+r',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fo o&ba+r',
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/re write/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54168',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/re%20write/',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/re write/index.php',
			'PHP_SELF' => '/~dzuelke/re write/index.php',
			'REQUEST_TIME' => 1164145525,
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54175',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/re%20write/index.php',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/re write/index.php',
			'PHP_SELF' => '/~dzuelke/re write/index.php',
			'REQUEST_TIME' => 1164145791,
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54177',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/re%20write/index.php?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/re write/index.php',
			'PHP_SELF' => '/~dzuelke/re write/index.php',
			'REQUEST_TIME' => 1164145811,
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54179',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/re%20write/index.php/fubar',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/re write/index.php/fubar',
			'REQUEST_TIME' => 1164145829,
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54182',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/re%20write/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/re write/index.php/fubar',
			'REQUEST_TIME' => 1164145870,
		)
	),
	array(
		'message' => 'Sub-directory w/ space, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/~dzuelke/re write/index.php',
		'basePath' => '/~dzuelke/re write/',
		'baseHref' => 'http://localhost/~dzuelke/re write/',
		'_ENV' => array (
		),
		'_GET' => array (
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_COOKIE' => 'locale=en',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.9 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '54185',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/re write/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.1.6',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'test=foo%20bar+baz',
			'REQUEST_URI' => '/~dzuelke/re%20write/index.php/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/~dzuelke/re write/index.php',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fo o&ba+r',
			'PHP_SELF' => '/~dzuelke/re write/index.php/fo o&ba+r',
			'REQUEST_TIME' => 1164145889,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_IF_MODIFIED_SINCE' => 'Mon, 28 Aug 2006 14:35:30 GMT',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61701',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/',
			'REQUEST_URI' => '/~dzuelke/rw/',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61703',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/~dzuelke/rw/fubar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '61705',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at 127.0.0.1 Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/fubar?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with query',
		'input' => '/fo o&ba+r',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_GET' => array (
			'/fo_o' => '',
			'ba_r' => '',
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/fo o&ba+r',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '62438',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => 'Apache/1.3.33 Server at localhost Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REQUEST_URI' => '/~dzuelke/rw/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with empty query (i.e. trailing question mark)',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64760',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721704,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query string and trailing ampersand',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
			'foo' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&foo',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64772',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&foo',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?foo&',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721757,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query string that only has a trailing ampersand',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64780',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?&',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721792,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand (no query string)',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64746',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721675,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand and query string',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
			'foo' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&&foo',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64767',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&&foo',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&?foo',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721729,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand and empty query string',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dominik/agavi/samples/pub',
		'basePath' => '/~dominik/agavi/samples/pub/',
		'baseHref' => 'http://zomg.lol.dev/~dominik/agavi/samples/pub/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Volumes/Sevenload/core/trunk/pub/',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; de-de) AppleWebKit/522.11.1 (KHTML, like Gecko) Version/3.0.3 Safari/522.12.1',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '64733',
			'SCRIPT_FILENAME' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'zomg.lol.dev',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '
		Apache/1.3.33 Server at zomg.lol.dev Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.2.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dominik/agavi/samples/pub/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&?',
			'SCRIPT_NAME' => '/~dominik/agavi/samples/pub/index.php',
			'PATH_TRANSLATED' => '/Users/dominik/Sites/agavi/samples/pub/index.php',
			'PHP_SELF' => '/~dominik/agavi/samples/pub/index.php',
			'REQUEST_TIME' => 1194721592,
		)
	),
);