<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/norewrite/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62109',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/norewrite/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62109',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1155053682,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62188',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62188',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1155054103,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62190',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62190',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1155054133,
			'argv' => 
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62199',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62199',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1155054183,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62201',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62201',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1155054202,
			'argv' => 
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'init' => array(
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62253',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/',
			'REQUEST_URI' => '/testing/david/rewrite/',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62253',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/',
			'REQUEST_URI' => '/testing/david/rewrite/',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1155054382,
			'argv' => 
			array (
				0 => '123qwe=/',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'init' => array(
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62383',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/fubar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62383',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1155055722,
			'argv' => 
			array (
				0 => '123qwe=/fubar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'init' => array(
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62387',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/fubar',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62387',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1155055752,
			'argv' => 
			array (
				0 => '123qwe=/fubar&foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query and overwrote path info query param',
		'input' => '/fubar',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'init' => array(
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_IF_MODIFIED_SINCE' => 'Tue, 08 Aug 2006 16:37:20 GMT',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar&123qwe=as%20df',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62390',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar&123qwe=as%20df',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar&123qwe=as%20df',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => 'as df',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_IF_MODIFIED_SINCE' => 'Tue, 08 Aug 2006 16:37:20 GMT',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar&123qwe=as%20df',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62390',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar&123qwe=as%20df',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar&123qwe=as%20df',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1155055802,
			'argv' => 
			array (
				0 => '123qwe=/fubar&foo=bar&123qwe=as%20df',
			),
			'argc' => 1,
		)
	)
);