<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/norewrite/',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62351',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/norewrite/',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62351',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1156779353,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62354',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62354',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1156779389,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62354',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62354',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1156779405,
			'argv' => 
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62358',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62358',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1156779429,
			'argv' => 
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62360',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62360',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1156779452,
			'argv' => 
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/testing/david/norewrite/index.php',
		'basePath' => '/testing/david/norewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/norewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.2.219',
			'REMOTE_PORT' => '57003',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '194.79.16.69',
			'SERVER_ADMIN' => 'root@sigmatic.fi',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'test=foo%20bar+baz',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fo o&ba+r',
			'ORIG_PATH_INFO' => '/fo o&ba+r',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
		),
		'_GET' => array (
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.2.219',
			'REMOTE_PORT' => '57003',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'SERVER_ADDR' => '194.79.16.69',
			'SERVER_ADMIN' => 'root@sigmatic.fi',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'test=foo%20bar+baz',
			'REQUEST_URI' => '/testing/david/norewrite/index.php/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fo o&ba+r',
			'ORIG_PATH_INFO' => '/fo o&ba+r',
			'ORIG_SCRIPT_NAME' => '/testing/david/norewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/norewrite/index.php',
			'PHP_SELF' => '/testing/david/norewrite/index.php',
			'REQUEST_TIME' => 1157082567,
			'argv' => 
			array (
				0 => 'test=foo%20bar',
				1 => 'baz',
			),
			'argc' => 2,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62371',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/',
			'REQUEST_URI' => '/testing/david/rewrite/',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'/' => '',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62371',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/',
			'REQUEST_URI' => '/testing/david/rewrite/',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1156779493,
			'argv' => 
			array (
				0 => '/',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62373',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62373',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1156779526,
			'argv' => 
			array (
				0 => '/fubar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62374',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fubar',
			'REMOTE_ADDR' => '88.64.5.58',
			'REMOTE_PORT' => '62374',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REQUEST_URI' => '/testing/david/rewrite/fubar?foo=bar',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1156779544,
			'argv' => 
			array (
				0 => '/fubar&foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with query',
		'input' => '/fo o&ba+r',
		'prefix' => '/testing/david/rewrite',
		'basePath' => '/testing/david/rewrite/',
		'baseHref' => 'http://www.veikkomakinen.com/testing/david/rewrite/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fo o&ba+r',
			'REMOTE_ADDR' => '88.64.2.219',
			'REMOTE_PORT' => '56996',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '194.79.16.69',
			'SERVER_ADMIN' => 'root@sigmatic.fi',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REQUEST_URI' => '/testing/david/rewrite/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'/fo_o' => '',
			'ba_r' => '',
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/testing/david/rewrite/fo o&ba+r',
			'REMOTE_ADDR' => '88.64.2.219',
			'REMOTE_PORT' => '56996',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'SERVER_ADDR' => '194.79.16.69',
			'SERVER_ADMIN' => 'root@sigmatic.fi',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo o&ba+r&test=foo%20bar+baz',
			'REQUEST_URI' => '/testing/david/rewrite/fo%20o&ba+r?test=foo%20bar+baz',
			'SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_NAME' => '/testing/david/rewrite/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/testing/david/rewrite/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/testing/david/rewrite/index.php',
			'REQUEST_TIME' => 1157082444,
			'argv' => 
			array (
				0 => '/fo o&ba',
				1 => 'r&test=foo%20bar',
				2 => 'baz',
			),
			'argc' => 3,
		)
	),
);