<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'cRfrKEI5IZQAAAV8BzIAAAAC',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61462',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180907450,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'bVtl5EI5IZQAAAmXXGAAAAAG',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61440',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180907387,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'c0wjZUI5IZQAAAV6As8AAAAA',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61473',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180907487,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query that contains two slashes',
		'input' => '/',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'ba//r',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'OQqIFkI5IZQAAAV7Be0AAAAB',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_IF_MODIFIED_SINCE' => 'Sun, 03 Jun 2007 22:45:50 GMT',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '63027',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=ba//r',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php?foo=ba//r',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180910804,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'dJOjb0I5IZQAAAV9CQAAAAAD',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61477',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fubar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fubar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fubar',
			'REQUEST_TIME' => 1180907508,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info that contains two slashes',
		'input' => '/fu//bar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'ha94pkI5IZQAAAmWWqwAAAAF',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61572',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fu//bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fu/bar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fu/bar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fu//bar',
			'REQUEST_TIME' => 1180907795,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'iqo@JkI5IZQAAAmYXZUAAAAH',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61596',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fubar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fubar',
			'REQUEST_TIME' => 1180907879,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info that contains two slashes and query',
		'input' => '/fu//bar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'jdn2KEI5IZQAAAV@CR4AAAAE',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61613',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fu//bar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fu/bar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fu/bar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fu//bar',
			'REQUEST_TIME' => 1180907932,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info that contains two slashes and query with two slashes',
		'input' => '/fu//bar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'ba//r',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'Q@VErkI5IZQAAAV6AtoAAAAA',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_IF_MODIFIED_SINCE' => 'Sun, 03 Jun 2007 22:46:10 GMT',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '63098',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=ba//r',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fu//bar?foo=ba//r',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fu/bar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fu/bar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fu//bar',
			'REQUEST_TIME' => 1180910987,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'l6RQtkI5IZQAAAV8BzUAAAAC',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61668',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fo%20o&ba+r?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => '/home/impl/public_html/fo o&ba+r',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fo o&ba+r',
			'REQUEST_TIME' => 1180908097,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info that contains two slashes and query',
		'input' => '/fo//o&bar',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'pkkmYkI5IZQAAAmWWq8AAAAF',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61783',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/fo//o&bar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/fo/o&bar',
			'PATH_TRANSLATED' => '/home/impl/public_html/fo/o&bar',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/fo//o&bar',
			'REQUEST_TIME' => 1180908342,
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info that contains two slashes after the & and query',
		'input' => '/foo&ba//r',
		'prefix' => '/tests/apache2.2-rewrite/index.php',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'UNIQUE_ID' => 'rSaCWUI5IZQAAAV@CSEAAAAE',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61817',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/index.php/foo&ba//r?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PATH_INFO' => '/foo&ba/r',
			'PATH_TRANSLATED' => '/home/impl/public_html/foo&ba/r',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php/foo&ba//r',
			'REQUEST_TIME' => 1180908457,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/' => '',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'v@o1kEI5IZQAAAnXKZEAAAAJ',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'v@o1kEI5IZQAAAnXKZEAAAAJ',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61935',
			'REDIRECT_QUERY_STRING' => '/',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180908772,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'wbS26EI5IZQAAAnYKQMAAAAK',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'wbS26EI5IZQAAAnYKQMAAAAK',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61947',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fubar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fubar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180908802,
		)
	),
	array(
		'expectFailure' => array(
			'prefix',
			'input',
			'basePath',
			'baseHref',
		),
		'message' => 'Sub-directory, rewritten, called path in dir with two slashes; THIS TEST IS EXPECTED TO FAIL, SEE #502!',
		'input' => '/fubar',
		'prefix' => '/tmp//rewrite',
		'basePath' => '/tmp//rewrite/',
		'baseHref' => 'http://ross.sandbox.zomglolkthxbai.net/tmp//rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Opera/9.21 (Windows NT 5.1; U; en)',
			'HTTP_HOST' => 'ross.sandbox.zomglolkthxbai.net',
			'HTTP_ACCEPT' => 'text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1',
			'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.9',
			'HTTP_ACCEPT_CHARSET' => 'iso-8859-1, utf-8, utf-16, *;q=0.1',
			'HTTP_ACCEPT_ENCODING' => 'deflate, gzip, x-gzip, identity, *;q=0',
			'HTTP_CONNECTION' => 'Keep-Alive, TE',
			'HTTP_TE' => 'deflate, gzip, chunked, identity, trailers',
			'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin',
			'SERVER_SIGNATURE' => '
		Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1 Server at ross.sandbox.zomglolkthxbai.net Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1',
			'SERVER_NAME' => 'ross.sandbox.zomglolkthxbai.net',
			'SERVER_ADDR' => '10.42.2.223',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '10.42.2.128',
			'DOCUMENT_ROOT' => '/home/ross/www/',
			'SERVER_ADMIN' => 'webmaster@localhost',
			'SCRIPT_FILENAME' => '/home/ross/www/tmp/rewrite/index.php',
			'REMOTE_PORT' => '2937',
			'REDIRECT_QUERY_STRING' => '/fubar',
			'REDIRECT_URL' => '/tmp//rewrite/fubar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar',
			'REQUEST_URI' => '/tmp//rewrite/fubar',
			'SCRIPT_NAME' => '/tmp/rewrite/index.php',
			'PHP_SELF' => '/tmp/rewrite/index.php',
			'REQUEST_TIME' => 1180957954,
			'argv' => 
			array (
				0 => '/fubar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with two slashes',
		'input' => '/fu//bar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fu/bar' => '',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'xD2m@kI5IZQAAAV9CQYAAAAD',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'xD2m@kI5IZQAAAV9CQYAAAAD',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61961',
			'REDIRECT_QUERY_STRING' => '/fu/bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fu//bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fu/bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fu//bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180908845,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'yeO5JkI5IZQAAAV7BesAAAAB',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'yeO5JkI5IZQAAAV7BesAAAAB',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '61991',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fubar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fubar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180908940,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query that contains two slashes',
		'input' => '/fubar',
		'prefix' => '/tmp/rewrite',
		'basePath' => '/tmp/rewrite/',
		'baseHref' => 'http://ross.sandbox.zomglolkthxbai.net/tmp/rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'ba//r',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Opera/9.21 (Windows NT 5.1; U; en)',
			'HTTP_HOST' => 'ross.sandbox.zomglolkthxbai.net',
			'HTTP_ACCEPT' => 'text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1',
			'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.9',
			'HTTP_ACCEPT_CHARSET' => 'iso-8859-1, utf-8, utf-16, *;q=0.1',
			'HTTP_ACCEPT_ENCODING' => 'deflate, gzip, x-gzip, identity, *;q=0',
			'HTTP_CONNECTION' => 'Keep-Alive, TE',
			'HTTP_TE' => 'deflate, gzip, chunked, identity, trailers',
			'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin',
			'SERVER_SIGNATURE' => '
		Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1 Server at ross.sandbox.zomglolkthxbai.net Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1',
			'SERVER_NAME' => 'ross.sandbox.zomglolkthxbai.net',
			'SERVER_ADDR' => '10.42.2.223',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '10.42.2.128',
			'DOCUMENT_ROOT' => '/home/ross/www/',
			'SERVER_ADMIN' => 'webmaster@localhost',
			'SCRIPT_FILENAME' => '/home/ross/www/tmp/rewrite/index.php',
			'REMOTE_PORT' => '2560',
			'REDIRECT_QUERY_STRING' => '/fubar&foo=ba//r',
			'REDIRECT_URL' => '/tmp/rewrite/fubar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fubar&foo=ba//r',
			'REQUEST_URI' => '/tmp/rewrite/fubar?foo=ba//r',
			'SCRIPT_NAME' => '/tmp/rewrite/index.php',
			'PHP_SELF' => '/tmp/rewrite/index.php',
			'REQUEST_TIME' => 1180952406,
			'argv' => 
			array (
				0 => '/fubar&foo=ba//r',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with two slashes with query',
		'input' => '/fu//bar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fu/bar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'yzjjWEI5IZQAAAV6AtgAAAAA',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'yzjjWEI5IZQAAAV6AtgAAAAA',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '62002',
			'REDIRECT_QUERY_STRING' => '/fu/bar&foo=bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fu//bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fu/bar&foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fu//bar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180908962,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with two slashes with query that contains two slashes',
		'input' => '/fu//bar',
		'prefix' => '/tmp/rewrite',
		'basePath' => '/tmp/rewrite/',
		'baseHref' => 'http://ross.sandbox.zomglolkthxbai.net/tmp/rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fu/bar' => '',
			'foo' => 'ba//r',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Opera/9.21 (Windows NT 5.1; U; en)',
			'HTTP_HOST' => 'ross.sandbox.zomglolkthxbai.net',
			'HTTP_ACCEPT' => 'text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1',
			'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.9',
			'HTTP_ACCEPT_CHARSET' => 'iso-8859-1, utf-8, utf-16, *;q=0.1',
			'HTTP_ACCEPT_ENCODING' => 'deflate, gzip, x-gzip, identity, *;q=0',
			'HTTP_CONNECTION' => 'Keep-Alive, TE',
			'HTTP_TE' => 'deflate, gzip, chunked, identity, trailers',
			'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin',
			'SERVER_SIGNATURE' => '
		Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1 Server at ross.sandbox.zomglolkthxbai.net Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1',
			'SERVER_NAME' => 'ross.sandbox.zomglolkthxbai.net',
			'SERVER_ADDR' => '10.42.2.223',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '10.42.2.128',
			'DOCUMENT_ROOT' => '/home/ross/www/',
			'SERVER_ADMIN' => 'webmaster@localhost',
			'SCRIPT_FILENAME' => '/home/ross/www/tmp/rewrite/index.php',
			'REMOTE_PORT' => '2553',
			'REDIRECT_QUERY_STRING' => '/fu/bar&foo=ba//r',
			'REDIRECT_URL' => '/tmp/rewrite/fu//bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fu/bar&foo=ba//r',
			'REQUEST_URI' => '/tmp/rewrite/fu//bar?foo=ba//r',
			'SCRIPT_NAME' => '/tmp/rewrite/index.php',
			'PHP_SELF' => '/tmp/rewrite/index.php',
			'REQUEST_TIME' => 1180952358,
			'argv' => 
			array (
				0 => '/fu/bar&foo=ba//r',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with three slashes',
		'input' => '/foo///bar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/foo/bar' => '',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => '8fopwUI5IZQAAAnWEKYAAAAI',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => '8fopwUI5IZQAAAnWEKYAAAAI',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '62202',
			'REDIRECT_QUERY_STRING' => '/foo/bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/foo///bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/foo/bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/foo///bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180909612,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with query',
		'input' => '/fo o&ba+r',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fo_o' => '',
			'ba_r' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => 'zdhjd0I5IZQAAAmWWrIAAAAF',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => 'zdhjd0I5IZQAAAmWWrIAAAAF',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '62014',
			'REDIRECT_QUERY_STRING' => '/fo o&ba+r&foo=bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fo o&ba+r',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo o&ba+r&foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fo%20o&ba+r?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180909006,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with two slashes with query',
		'input' => '/fo//o&bar',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fo/o' => '',
			'bar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => '1IisWUI5IZQAAAmXXGcAAAAG',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => '1IisWUI5IZQAAAmXXGcAAAAG',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '62047',
			'REDIRECT_QUERY_STRING' => '/fo/o&bar&foo=bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/fo//o&bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fo/o&bar&foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/fo//o&bar?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180909118,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with two slashes after the & with query',
		'input' => '/foo&ba//r',
		'prefix' => '/tests/apache2.2-rewrite',
		'basePath' => '/tests/apache2.2-rewrite/',
		'baseHref' => 'http://impl.user.compass.zomglolkthxbai.com/tests/apache2.2-rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/foo' => '',
			'ba/r' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'REDIRECT_UNIQUE_ID' => '13IksUI5IZQAAAV@CSUAAAAE',
			'REDIRECT_STATUS' => '200',
			'UNIQUE_ID' => '13IksUI5IZQAAAV@CSUAAAAE',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/419 (KHTML, like Gecko) Safari/419.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'impl.user.compass.zomglolkthxbai.com',
			'PATH' => '/sbin:/bin:/usr/sbin:/usr/bin',
			'SERVER_SIGNATURE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8 Server at impl.user.compass.zomglolkthxbai.com Port 80
		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (FreeBSD) mod_ssl/2.2.4 OpenSSL/0.9.7e-p1 DAV/2 proxy_html/2.5 PHP/5.2.2 with Suhosin-Patch mod_ruby/1.2.6 Ruby/1.8.6(2007-03-13) mod_python/3.3.1 Python/2.4.4 mod_perl/2.0.3 Perl/v5.8.8',
			'SERVER_NAME' => 'impl.user.compass.zomglolkthxbai.com',
			'SERVER_ADDR' => '66.57.33.148',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '80.135.2.151',
			'DOCUMENT_ROOT' => 'www/apache22/data',
			'SERVER_ADMIN' => 'webmaster@compass.zomglolkthxbai.com',
			'SCRIPT_FILENAME' => '/home/impl/public_html/tests/apache2.2-rewrite/index.php',
			'REMOTE_PORT' => '62064',
			'REDIRECT_QUERY_STRING' => '/foo&ba/r&foo=bar',
			'REDIRECT_URL' => '/tests/apache2.2-rewrite/foo&ba//r',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/foo&ba/r&foo=bar',
			'REQUEST_URI' => '/tests/apache2.2-rewrite/foo&ba//r?foo=bar',
			'SCRIPT_NAME' => '/tests/apache2.2-rewrite/index.php',
			'PHP_SELF' => '/tests/apache2.2-rewrite/index.php',
			'REQUEST_TIME' => 1180909167,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with two slashes and an uber complicated query with, yeah, two slashes',
		'input' => '/fu//bar',
		'prefix' => '/tmp/rewrite',
		'basePath' => '/tmp/rewrite/',
		'baseHref' => 'http://ross.sandbox.zomglolkthxbai.net/tmp/rewrite/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/fu/bar' => '',
			'foo' => 'bar ba//z lol',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Opera/9.21 (Windows NT 5.1; U; en)',
			'HTTP_HOST' => 'ross.sandbox.zomglolkthxbai.net',
			'HTTP_ACCEPT' => 'text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1',
			'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en;q=0.9',
			'HTTP_ACCEPT_CHARSET' => 'iso-8859-1, utf-8, utf-16, *;q=0.1',
			'HTTP_ACCEPT_ENCODING' => 'deflate, gzip, x-gzip, identity, *;q=0',
			'HTTP_CONNECTION' => 'Keep-Alive, TE',
			'HTTP_TE' => 'deflate, gzip, chunked, identity, trailers',
			'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin',
			'SERVER_SIGNATURE' => '
		Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1 Server at ross.sandbox.zomglolkthxbai.net Port 80

		',
			'SERVER_SOFTWARE' => 'Apache/2.2.4 (Unix) DAV/2 SVN/1.4.3 PHP/5.2.1',
			'SERVER_NAME' => 'ross.sandbox.zomglolkthxbai.net',
			'SERVER_ADDR' => '10.42.2.223',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '10.42.2.128',
			'DOCUMENT_ROOT' => '/home/ross/www/',
			'SERVER_ADMIN' => 'webmaster@localhost',
			'SCRIPT_FILENAME' => '/home/ross/www/tmp/rewrite/index.php',
			'REMOTE_PORT' => '2947',
			'REDIRECT_QUERY_STRING' => '/fu/bar&foo=bar%20ba//z+lol',
			'REDIRECT_URL' => '/tmp/rewrite/fu//bar',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/fu/bar&foo=bar%20ba//z+lol',
			'REQUEST_URI' => '/tmp/rewrite/fu//bar?foo=bar%20ba//z+lol',
			'SCRIPT_NAME' => '/tmp/rewrite/index.php',
			'PHP_SELF' => '/tmp/rewrite/index.php',
			'REQUEST_TIME' => 1180958000,
			'argv' => 
			array (
				0 => '/fu/bar&foo=bar%20ba//z',
				1 => 'lol',
			),
			'argc' => 2,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with empty query (i.e. trailing question mark)',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=mt51ovf249sihgmbf34bv2k211; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '62154',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194627705,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query string and trailing ampersand',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
			'foo' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=mt51ovf249sihgmbf34bv2k211; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '62156',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&foo',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&foo',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?foo&',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194627946,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query string that only has a trailing ampersand',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=j37int79ma06iclrriv7lls982; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '60174',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342?&',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194858160,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand (no query string)',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=mt51ovf249sihgmbf34bv2k211; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '62157',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194628032,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand and query string',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
			'foo' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=mt51ovf249sihgmbf34bv2k211; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '62438',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&&foo',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&&foo',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&?foo',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194632364,
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with trailing ampersand and empty query string',
		'input' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
		'prefix' => '/~dzuelke/ag0.11sa',
		'basePath' => '/~dzuelke/ag0.11sa/',
		'baseHref' => 'http://localhost/~dzuelke/ag0.11sa/',
		'_ENV' => array (
		),
		'_GET' => array (
			'/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342' => '',
		),
		'_SERVER' => array (
			'REDIRECT_STATUS' => '200',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/523.10.3 (KHTML, like Gecko) Version/3.0.4 Safari/523.10',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_COOKIE' => 'Agavi=mt51ovf249sihgmbf34bv2k211; locale=en',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
			'SERVER_SIGNATURE' => '',
			'SERVER_SOFTWARE' => 'Apache/2.2.6 (Unix) mod_ssl/2.2.6 OpenSSL/0.9.7l DAV/2 PHP/5.2.4',
			'SERVER_NAME' => 'localhost',
			'SERVER_ADDR' => '::1',
			'SERVER_PORT' => '80',
			'REMOTE_ADDR' => '::1',
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'SERVER_ADMIN' => 'you@example.com',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/ag0.11sa/index.php',
			'REMOTE_PORT' => '62439',
			'REDIRECT_QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REDIRECT_URL' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&',
			'REQUEST_URI' => '/~dzuelke/ag0.11sa/en/products/buy-cheap-brains-at-agavi-dot-org/4815162342&?',
			'SCRIPT_NAME' => '/~dzuelke/ag0.11sa/index.php',
			'PHP_SELF' => '/~dzuelke/ag0.11sa/index.php',
			'REQUEST_TIME' => 1194632442,
		)
	),
);