<?php return array(
	array(
		'message' => 'Document root, no rewrite, called root',
		'parseMethod' => 'parseApacheCgiNoRewrite',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62449',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62449',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155056471,
			'argv' =>
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php',
		'parseMethod' => 'parseApacheCgiNoRewrite',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62557',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62557',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155057474,
			'argv' =>
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with query',
		'parseMethod' => 'parseApacheCgiNoRewrite',
		'input' => '/',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62560',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62560',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155057505,
			'argv' =>
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with path info',
		'parseMethod' => 'parseApacheCgiNoRewrite',
		'input' => '/fubar',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62563',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php/fubar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62563',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/index.php/fubar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155057535,
			'argv' =>
			array (
			),
			'argc' => 0,
		)
	),
	array(
		'message' => 'Document root, no rewrite, called index.php with path info and query',
		'parseMethod' => 'parseApacheCgiNoRewrite',
		'input' => '/fubar',
		'prefix' => '/index.php',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62565',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '62565',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'ORIG_PATH_TRANSLATED' => '/www/asiakkaat/veikkoma/public_html/fubar',
			'ORIG_PATH_INFO' => '/fubar',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155057551,
			'argv' =>
			array (
				0 => 'foo=bar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Document root, rewritten, called root',
		'parseMethod' => 'parseApacheCgiRewrite',
		'input' => '/',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'init' => array (
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64176',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64176',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/',
			'REQUEST_URI' => '/',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155061808,
			'argv' =>
			array (
				0 => '123qwe=/',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Document root, rewritten, called path',
		'parseMethod' => 'parseApacheCgiRewrite',
		'input' => '/fubar',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'init' => array (
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64176',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar',
			'REQUEST_URI' => '/fubar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/fubar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64176',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar',
			'REQUEST_URI' => '/fubar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155061824,
			'argv' =>
			array (
				0 => '123qwe=/fubar',
			),
			'argc' => 1,
		)
	),
	array(
		'message' => 'Document root, rewritten, called path with query',
		'parseMethod' => 'parseApacheCgiRewrite',
		'input' => '/fubar',
		'prefix' => '',
		'basePath' => '/',
		'baseHref' => 'http://www.veikkomakinen.com/',
		'init' => array (
			'path_info_parameter' => '123qwe'
		),
		'_ENV' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64179',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REQUEST_URI' => '/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
		),
		'_GET' => array (
			'123qwe' => '/fubar',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'PATH' => '/usr/local/bin:/usr/bin:/bin',
			'DOCUMENT_ROOT' => '/www/asiakkaat/veikkoma/public_html',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'www.veikkomakinen.com',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'REDIRECT_QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/fubar',
			'REMOTE_ADDR' => '88.64.13.5',
			'REMOTE_PORT' => '64179',
			'SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'SERVER_ADDR' => '123.123.123.123',
			'SERVER_ADMIN' => 'test@agavi.org',
			'SERVER_NAME' => 'www.veikkomakinen.com',
			'SERVER_PORT' => '80',
			'SERVER_SOFTWARE' => 'Apache/1.3.34',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '123qwe=/fubar&foo=bar',
			'REQUEST_URI' => '/fubar?foo=bar',
			'SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_NAME' => '/index.php',
			'ORIG_SCRIPT_FILENAME' => '/www/asiakkaat/veikkoma/public_html/index.php',
			'PATH_INFO' => '',
			'PATH_TRANSLATED' => '',
			'PHP_SELF' => '/index.php',
			'REQUEST_TIME' => 1155061847,
			'argv' =>
			array (
				0 => '123qwe=/fubar&foo=bar',
			),
			'argc' => 1,
		)
	)
);