<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50148',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50183',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/index.php',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50193',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/index.php?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_TRANSLATED' => '/Users/dzuelke/Sites/rw/index.php',
			'PHP_SELF' => '/~dzuelke/rw/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50224',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/index.php/fubar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw/index.php',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50236',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/index.php/fubar?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50246',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/',
			'PHP_SELF' => '/~dzuelke/rw/index.php/',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50269',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => '',
			'REQUEST_URI' => '/~dzuelke/rw/fubar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/~dzuelke/rw',
		'basePath' => '/~dzuelke/rw/',
		'baseHref' => 'http://localhost/~dzuelke/rw/',
		'_ENV' => array (
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'PWD' => '/',
			'SHLVL' => '3',
			'_' => '/usr/sbin/httpd',
		),
		'_SERVER' => array (
			'DOCUMENT_ROOT' => '/Library/WebServer/Documents',
			'HTTP_ACCEPT' => '*/*',
			'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3',
			'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/System/Library/CoreServices',
			'REDIRECT_QUERY_STRING' => 'foo=bar',
			'REDIRECT_STATUS' => '200',
			'REDIRECT_URL' => '/~dzuelke/rw/fubar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_PORT' => '50289',
			'SCRIPT_FILENAME' => '/Users/dzuelke/Sites/rw/index.php',
			'SERVER_ADDR' => '127.0.0.1',
			'SERVER_ADMIN' => '[no address given]',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '80',
			'SERVER_SIGNATURE' => '<ADDRESS>Apache/1.3.33 Server at localhost Port 80</ADDRESS>
		',
			'SERVER_SOFTWARE' => 'Apache/1.3.33 (Darwin) PHP/5.0.4',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'REQUEST_METHOD' => 'GET',
			'QUERY_STRING' => 'foo=bar',
			'REQUEST_URI' => '/~dzuelke/rw/fubar?foo=bar',
			'SCRIPT_NAME' => '/~dzuelke/rw/index.php',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => '/Library/WebServer/Documents/fubar',
			'PHP_SELF' => '/~dzuelke/rw/index.php/fubar',
		)
	),
);