<?php return array(
	array(
		'message' => 'Sub-directory, no rewrite, called directory',
		'input' => '/',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php',
		'input' => '/',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with query',
		'input' => '/',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info',
		'input' => '/fubar',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php/fubar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => 'C:/htdocs/fubar',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fubar',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fubar',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php/fubar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => 'C:/htdocs/fubar',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fubar',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fubar',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with path info and query',
		'input' => '/fubar',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php/fubar?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => 'C:/htdocs/fubar',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fubar',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fubar',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/index.php/fubar?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fubar',
			'PATH_TRANSLATED' => 'C:/htdocs/fubar',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fubar',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fubar',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, no rewrite, called index.php with special path info and query',
		'input' => '/fo o&ba+r',
		'prefix' => '/agavi/trunk/samples/pub/index.php',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => 'C:/htdocs/fo o&ba+r',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fo o&ba+r',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fo o&ba+r',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATH_INFO' => '/fo o&ba+r',
			'PATH_TRANSLATED' => 'C:/htdocs/fo o&ba+r',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => 'foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php\\fo o&ba+r',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php/fo o&ba+r',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called directory',
		'input' => '/',
		'prefix' => '/agavi/trunk/samples/pub',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'/' => '',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_CACHE_CONTROL' => 'max-age=0',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path',
		'input' => '/fubar',
		'prefix' => '/agavi/trunk/samples/pub',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fubar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fubar&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'/fubar' => '',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fubar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fubar&',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called path with query',
		'input' => '/fubar',
		'prefix' => '/agavi/trunk/samples/pub',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fubar?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'/fubar' => '',
			'foo' => 'bar',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fubar?foo=bar',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fubar&foo=bar',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
	array(
		'message' => 'Sub-directory, rewritten, called special path with query',
		'input' => '/fo o&ba+r',
		'prefix' => '/agavi/trunk/samples/pub',
		'basePath' => '/agavi/trunk/samples/pub/',
		'baseHref' => 'http://localhost:81/agavi/trunk/samples/pub/',
		'_ENV' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fo%20o&ba+r?test=foo%20bar+baz',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fo%20o&ba+r&test=foo%20bar+baz',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
		),
		'_GET' => array (
			'/fo_o' => '',
			'ba_r' => '',
			'test' => 'foo bar baz',
		),
		'_SERVER' => array (
			'ALLUSERSPROFILE' => 'C:\\Dokumente und Einstellungen\\All Users',
			'APR_ICONV_PATH' => 'C:\\Programme\\Subversion\\iconv',
			'CLASSPATH' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'CommonProgramFiles' => 'C:\\Programme\\Gemeinsame Dateien',
			'COMPUTERNAME' => 'WOMBERT',
			'ComSpec' => 'C:\\WINDOWS\\system32\\cmd.exe',
			'CONTENT_LENGTH' => '0',
			'FP_NO_HOST_CHECK' => 'NO',
			'FSHARP_TARGET_VS_VER' => '7.1',
			'GATEWAY_INTERFACE' => 'CGI/1.1',
			'HTTP_ACCEPT' => 'text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5',
			'HTTP_ACCEPT_LANGUAGE' => 'de-de,de;q=0.8,en-us;q=0.5,en;q=0.3',
			'HTTP_CONNECTION' => 'keep-alive',
			'HTTP_HOST' => 'localhost:81',
			'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.7.12) Gecko/20050919 Firefox/1.0.7',
			'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
			'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
			'HTTP_KEEP_ALIVE' => '300',
			'HTTP_X_REWRITE_URL' => '/agavi/trunk/samples/pub/fo%20o&ba+r?test=foo%20bar+baz',
			'HTTPS' => 'off',
			'INCLUDE' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\include\\',
			'INSTANCE_ID' => '1',
			'LIB' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\SDK\\v1.1\\Lib\\',
			'LOCAL_ADDR' => '127.0.0.1',
			'NUMBER_OF_PROCESSORS' => '1',
			'OS' => 'Windows_NT',
			'Path' => 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\IM;C:\\Programme\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Programme\\Microsoft Office\\OFFICE11\\Business Contact Manager\\;C:\\Programme\\Subversion\\bin;c:\\Programme\\php;C:\\Programme\\QuickTime\\QTSystem\\',
			'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH',
			'PROCESSOR_ARCHITECTURE' => 'x86',
			'PROCESSOR_IDENTIFIER' => 'x86 Family 15 Model 2 Stepping 9, GenuineIntel',
			'PROCESSOR_LEVEL' => '15',
			'PROCESSOR_REVISION' => '0209',
			'ProgramFiles' => 'C:\\Programme',
			'QTJAVA' => 'C:\\Programme\\Java\\jre1.5.0\\lib\\ext\\QTJava.zip',
			'QUERY_STRING' => '/fo%20o&ba+r&test=foo%20bar+baz',
			'REMOTE_ADDR' => '127.0.0.1',
			'REMOTE_HOST' => '127.0.0.1',
			'REQUEST_METHOD' => 'GET',
			'SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SERVER_NAME' => 'localhost',
			'SERVER_PORT' => '81',
			'SERVER_PORT_SECURE' => '0',
			'SERVER_PROTOCOL' => 'HTTP/1.1',
			'SERVER_SOFTWARE' => 'Microsoft-IIS/5.1',
			'SystemDrive' => 'C:',
			'SystemRoot' => 'C:\\WINDOWS',
			'TEMP' => 'C:\\WINDOWS\\TEMP',
			'TMP' => 'C:\\WINDOWS\\TEMP',
			'USERPROFILE' => 'C:\\Dokumente und Einstellungen\\LocalService',
			'VS71COMNTOOLS' => 'c:\\Programme\\Microsoft Visual Studio .NET 2003\\Common7\\Tools\\',
			'windir' => 'C:\\WINDOWS',
			'ORIG_PATH_TRANSLATED' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'ORIG_PATH_INFO' => '/agavi/trunk/samples/pub/index.php',
			'ORIG_SCRIPT_NAME' => '/agavi/trunk/samples/pub/index.php',
			'SCRIPT_FILENAME' => 'C:\\htdocs\\agavi\\trunk\\samples\\pub\\index.php',
			'PHP_SELF' => '/agavi/trunk/samples/pub/index.php',
		)
	),
);