<?php
// auth-generated by FactoryConfigHandler
// date: 05/20/2005 16:00:10
if (self::$instance->controller instanceof ConsoleController)
{

	self::$instance->request = Request::newInstance('ConsoleRequest');
	self::$instance->storage = Storage::newInstance('SessionStorage');
	self::$instance->user = User::newInstance('BasicSecurityUser');
	self::$instance->request->initialize(self::$instance, null);
	self::$instance->storage->initialize(self::$instance, null);
	self::$instance->user->initialize(self::$instance, null);

	if (AG_USE_SECURITY) {
		self::$instance->securityFilter = SecurityFilter::newInstance('BasicSecurityFilter');
		self::$instance->securityFilter->initialize(self::$instance);
	}

	return;
}
if (self::$instance->controller instanceof Controller)
{

	self::$instance->request = Request::newInstance('WebRequest');
	self::$instance->storage = Storage::newInstance('SessionStorage');
	self::$instance->user = User::newInstance('BasicSecurityUser');
	self::$instance->request->initialize(self::$instance, null);
	self::$instance->storage->initialize(self::$instance, null);
	self::$instance->user->initialize(self::$instance, null);

	if (AG_USE_SECURITY) {
		self::$instance->securityFilter = SecurityFilter::newInstance('BasicSecurityFilter');
		self::$instance->securityFilter->initialize(self::$instance);
	}

	return;
}
?>